### ISSUE TITLE
User-facing APIs for `_request_for_retry` and `_normalize_etag`

### ISSUE THREAD

**Issue by LysandreJik** [huggingface/huggingface_hub#1028]
In `transformers`, we are currently leveraging three private methods (used [here](https://github.com/huggingface/transformers/blob/ab663b227490ee82fe944bbf3680d26fd53b337c/src/transformers/utils/hub.py#L934-L951)):

- `_raise_for_status`
- `_request_for_retry`
- `_normalize_etag`

The first of these is being formalized in https://github.com/huggingface/huggingface_hub/pull/1019 with a `hf_raise_for_status` public-facing method. This is great as from transformers' side we're certain that this method will be stable and won't have breaking changes in the coming months.

I wonder if the same could be done with `_request_for_retry` and `_normalize_etag`, so that `transformers` could 100% rely on `huggingface_hub` without needing to juggle with releases when APIs break.

WDYT @Wauplin?

If that is not possible, maybe we could go one step further and implement the method we're using in `transformers` (`get_hub_metadata`, which returns the commit hash and associated etag for a given url) directly in `huggingface_hub`.

cc @sgugger

**Comment by Wauplin** [comment]
Hi @LysandreJik , thanks for opening this ticket ! I also wanted to bring up this subject recently but didn't know where to start :grin: 

So yes, I'm definitely in favor of reducing as much as possible the use of private methods by making some of them "officially supported". About the `get_hub_metadata` I'm fine with having it in `huggingface_hub` so that "_normalize_etag" and "_request_for_retry" can stay private. Do you think that's all the occurrences of private methods ?

**Comment by sgugger** [comment]
Yes, `_normalize_etag` and `_raise_for_status` are only used in `get_hub_metadata`. So implementing this directly in `huggingface_hub` would remove the need to use those two private methods. Plus it's probably useful for other users.
