### ISSUE TITLE
Add Secrets via API on hf_api

### ISSUE THREAD

**Issue by radames** [huggingface/huggingface_hub#1234]
Since now it's possible to add Secrets via API it would be nice to have this added to the library.

```
curl 'https://huggingface.co/api/spaces/$namespace/$repo/secrets' -X POST -H 'Authorization: Bearer $access_token' -H 'Content-Type: application/json' --data-raw '{"key":"$key","value":"$value"}'

delete (-X DELETE)
```

**Comment by radames** [comment]
Since they're similar, maybe we could also add setting the hardware flavor into the api

```
curl 'https://huggingface.co/api/spaces/$namespace/$repo/hardware' -X POST -H 'Authorization: Bearer $access_token' -H 'Content-Type: application/json' --data-raw '{"flavor": "t4-medium"}'
```

These are two ending points that we're using on this Space Space creator https://huggingface.co/spaces/anzorq/sd-space-creator

maybe it could args inside the `create_repot` method? 

```
create_repo(
    repo_id=model_id,
    exist_ok=update,
    repo_type="space",
    space_sdk="gradio",
    flavor="t4-medium"
    secrets={"SECRETA":"asd", "SECRETB":"asd"}
)
```

**Comment by Wauplin** [comment]
Thanks @radames for the suggestions ! This makes indeed a lot of sense. I played a bit with the Spaces API to see what we can include in `huggingface_hub`. The HTTP endpoints seem quite complete already as we can:
- get current state (`GET /runtime`): RUNNING, BUILDING,...
- get current and requested hardware (`GET /runtime`)
- get current secrets (`GET /secrets`)
- set new secret (`POST /secrets`)
- delete secret (`DELETE /secrets`)
- request new hardware (`POST /hardware`)


### 1. What do you think about a few new helpers in `HfApi` ?

```py
class SpaceConfig:
    secrets: Dict[str, str]
    current_state: Literal or Enum
    current_hardware: Literal or Enum
    requested_hardware: Literal or Enum

class HfApi:
    (...)

    def get_space_config(repo_id: str) -> SpaceConfig:
        (...)

    def request_space_hardware(repo_id: str, hardware: Literal) -> None:
        (...)

    def set_space_secrets(repo_id: str, secrets: Dict[str, str]) -> None:
        # Handles both additions and deletions
        # Each addition/deletion is atomic so this method would not be transactional
        # (e.g.: might end up in a weird state if it fails)

    def add_space_secret(repo_id: str, key: str, value: str) -> None:
        # Atomic update

    def delete_space_secret(repo_id: str, key: str) -> None:
        # Atomic update
```

### 2. Additional suggestion: a less verbose `SpaceApi`

Otherwise I'm starting to consider the idea of having a `SpaceApi` object. Something like this (really just an suggestion):
```py
api = HfApi(token="hf_***").space(repo_id="...")

api.get_config()
api.request_hardware("t4-medium")
api.set_secrets({"foo": "bar", "hello": "world"})
api.add_secret("foo": "bar2")
api.delete_secret("foo")
```

We wouldn't have to repeat the `repo_id` and `space` all the time. This suggestion is a bit orthogonal and could be done later (it is more a design decision at this point since we could do the same for models and datasets as well).


WDTY ? (also cc @LysandreJik @osanseviero)
