### ISSUE TITLE
Dealing with requests 2.28+ and SSL

### ISSUE THREAD

**Issue by ashic** [huggingface/huggingface_hub#1271]
We're in a corporate network using zscaler on dev machines, and various ci servers using self signed certs. For non-prod environments, we've been using `CURL_CA_BUNDLE=''` to bypass ssl verification from `requests`. However, this is now deemed a bug (which it arguably should be) and from requests=2.28 onwards, this is no longer supported. As such, we can't download models using the huggingface_hub library. 

Requests still supports disabling verification, but that's through an explicit verify parameter. While the _request_wrapper function of file_download.py does have a **params argument that's not passed from things like hf_hub_download and cached_download. As a result, if the latest version of requests is installed, there is no way to download a model using the libraries available. 

In terms of resolution, I can think of a few approaches:

1. Add a verify parameter to top level functions that explicitly set the verify parameter to request. 
2. Take a requests Session (or a session factory) as a parameter to top level functions, and use a passed in session instead of creating new ones automatically. 
3. Support an environment variable that will be used to set verify on requests. 

(For those experiencing this problem now, forcing a prior version via pip install "requests<2.28" will allow bypassing with the env var.)

**Comment by Wauplin** [comment]
Hi @ashic, I have looked a bit at your issue. I'm quite unsure yet if we want to add a `verify` argument to our top-level functions `hf_hub_download` and `snapshot_download`. Maybe I'm mistaken but the use case seems quite niche to me. As a solution already exists ([pin version to requests<2.28](https://github.com/psf/requests/issues/6071#issuecomment-1073021639)), I'd prefer not to add complexity to `huggingface_hub` (that would need to be integrated in dependent libraries as well).

**Comment by Wauplin** [comment]
I'm closing this issue as "won't fix" as no news since 2 months (see [above](https://github.com/huggingface/huggingface_hub/issues/1271#issuecomment-1355091882) for reasons). Please open it again if needed.

**Comment by mickg10** [comment]
Hi @Wauplin — would you consider reopening this? The landscape has shifted a bit since 2022 and I think the case for a small env-var escape hatch is stronger now.

  **What changed:**

  - v1.0 migrated from `requests` to `httpx`, so the old `CURL_CA_BUNDLE=""` / `REQUESTS_CA_BUNDLE` workarounds no longer apply.
  - The `requests<2.28` pin isn't reachable anymore either, since `huggingface_hub` 1.x doesn't depend on `requests` at all.
  - `set_client_factory` is great for library users, but it's a Python-only hook — the `hf` CLI (and especially `uvx hf …`) has no way to reach it.

  **Concrete repro on a corporate TLS-inspecting network (Fortinet, Zscaler, Netskope, etc.):**

  ```
  $ uvx hf download some-org/some-model
  httpcore.ConnectError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed:
      self-signed certificate in certificate chain
  ```

  In these environments the user typically can't modify the system CA store (no root, ephemeral `uvx` venv, locked-down container, etc.), so `SSL_CERT_FILE` alone isn't always a way out.

  **We could : ** plumb two env vars through `default_client_factory` / `default_async_client_factory` in `utils/_http.py`:

  ```python
  def default_client_factory() -> httpx.Client:
      kwargs = dict(
          event_hooks={"request": [hf_request_event_hook]},
          follow_redirects=True,
          timeout=None,
      )
      if os.environ.get("HF_HUB_DISABLE_SSL_VERIFICATION", "").lower() in ("1", "true", "yes"):
          kwargs["verify"] = False
      elif ca := os.environ.get("HF_HUB_CA_BUNDLE"):
          kwargs["verify"] = ca
      return httpx.Client(**kwargs)
  ```

  - opt-in, default behavior unchanged.
  - Uses `httpx`'s existing `verify=` knob .
  - Also helps the `hf-xet` path noted in #3530, since it shares the client factory.
  - `HF_HUB_CA_BUNDLE` covers the "I have the corporate CA but can't install it system-wide" case; `HF_HUB_DISABLE_SSL_VERIFICATION` is the last-resort escape hatch (with the usual caveats documented).

Thoughts?

**Comment by julien-c** [comment]
What's the use case for doing MITM/self-signing certificates? (If it's in a corporate setting, I would encourage you to get in touch with our enterprise team)

**Comment by mickg10** [comment]
Corporate - but note that shadow IT is a thing. In many big corporations a developer tries to engage via procurement - not happening. If a project is using hf, then eventually there will be pressure to actually get it through jfrog or reach out directly - but typically shadow IT is the way in there.

This is basically making it harder for shadow IT to use it - hence the suggestions to get it simplified.

**Comment by julien-c** [comment]
@mickg10 got it, understand
