### ISSUE TITLE
`snapshot_download` does not show the name of the files downloaded in parallel

### ISSUE THREAD

**Issue by sgugger** [huggingface/huggingface_hub#1281]
I was running a code sample sent by a user for a bug and realized that `snapshot_download` uses some parallelism (ncie!) but doesn't give the name of the file downloaded as a result, see screenshot:
![image](https://user-images.githubusercontent.com/35901082/209292918-247a9798-926a-4e12-89b2-2210ea584edf.png)

This was by executing:

```py
from huggingface_hub import snapshot_download

model_path = snapshot_download("EleutherAI/gpt-neox-20b")
```

cc @Wauplin

**Comment by Wauplin** [comment]
Yes, thanks for reporting @sgugger :+1: 
This happens when the file is downloaded from S3 (LFS files). I fixed it as part of https://github.com/huggingface/huggingface_hub/pull/1267 (see https://github.com/huggingface/huggingface_hub/pull/1267#discussion_r1049439499). Fix will be available in next release :)

**Comment by sgugger** [comment]
Great, thanks and sorry for the dupe issue then.

**Comment by Wauplin** [comment]
No worries ! It was not documented anywhere :)
