### ISSUE TITLE
Inconsistency between list_models and list_spaces

### ISSUE THREAD

**Issue by osanseviero** [huggingface/huggingface_hub#1419]
If I do

```
repos = api.list_spaces(author="hackathon-somos-nlp-2023")
```

The `SpaceInfo` objects I get contain the `likes` attribute. If I do

```
api.list_models(author="hackathon-somos-nlp-2023")
```

The `ModelInfo` objects don't contain this attribute. Setting `full` is required to get `likes`. I would suggest to be consistent and have `likes` in both.

**Comment by julien-c** [comment]
cc @coyotte508 ;)

**Comment by coyotte508** [comment]
@Wauplin you can use the `expand` query param to select fields returned

**Comment by Wauplin** [comment]
@coyotte508 @osanseviero I've looked into this issue a bit. I made a script to check all inconsistencies by listing the fields returned by default and those that are optional (ie. returned when `full=True`). Here is the output: 

```
✅ Default in model is consistent with optional in dataset.
❌ Default in model but optional in space: {'tags'}
❌ Default in dataset but optional in model: {'downloads'}
❌ Default in dataset but optional in space: {'tags', 'cardData'}
❌ Default in space but optional in model: {'likes'}
❌ Default in space but optional in dataset: {'likes'}
```

To be consistent across all 3 methods, we should:
- return **downloads** and **likes** by default on the `/api/models` endpoint
- return **likes** by default on the `/api/datasets` endpoint
- return **tags** and **cardData** by default on the `/api/spaces` endpoint

That being said, I've tried the suggested `expand` parameter. My problem with it is that if I do https://huggingface.co/api/models?expand[]=likes&expand[]=downloads&limit=1 I will only get the _likes_ and _downloads_ fields instead of having the default ones plus those two.

What I could do is to use expand with all the current default + likes + downloads but that would make `huggingface_hub` very constrained. If a new default field is added server-side, I would need to update `hfh` to add the field to the `expand` list. This is against the current philosophy which is "if a field is added server-side", older versions of `hfh` should support it out of the box.

**Comment by coyotte508** [comment]
> To be consistent across all 3 methods, we should:
> 
>     * return **downloads** and **likes** by default on the `/api/models` endpoint
>     * return **likes** by default on the `/api/datasets` endpoint
>     * return **tags** and **cardData** by default on the `/api/spaces` endpoint

WDYT @Pierrci @julien-c ? 

> So my suggestions for the inconsistency issue are either:
> 
>     1. we update the "expand" behavior server-side to _append_ fields instead of replacing them + we update `huggingface_hub` accordingly
> 
>     2. we fix it server-side by adding the missing default fields (downloads/likes for models, likes for datasets and tags/cardData for spaces)
> 
>     3. we fix the requested fields in `huggingface_hub` to be consistent. Drawback: the fields are hardcoded => less flexible for retro-compatibility when new fields are added
> 
>     4. we don't care about it? confused
> 
> In any case, I think I'll push the consistency script so that we can rerun it regularly (not in every CI though).
> 
> What's your opinion @julien-c @coyotte508 @osanseviero. I'd rather prefer 1. so that consistency doesn't have to be necessarily handled server-side in the future. Otherwise I'd prefer 2. rather than 3. or 4.

@Wauplin I'm not sure we're going to add new fields in the list endpoints. But we could do a variation on `1`: add a "defaultFields" option to expand: `&expand[]=defaultFields`, so you could do `&expand[]=defaultFields&expand[]=likes&expand[]=downloads` for the models. Not that we'll still not return the deprecated `modelId` even if `expand` is set :sweat_smile: 

WDYT?

**Comment by Wauplin** [comment]
> I'm not sure we're going to add new default fields in the listing endpoints.

If that's the case then maybe we should hardcode them in `huggingface_hub`. The advantage I see in that is to be explicit when anyone reading the code (+we would have explicit attributes for `ModelInfo` `DatasetInfo` `SpaceInfo` instances.
And keep the "check inconsistencies script" just in case to check if the list of default fields evolves and we forgot to update `hfh` accordingly.

 > But we could do a variation on 1: add a "defaultFields" option to expand:

Would work as well but maybe let's not complexify the API and hardcode things client-side instead.

**Comment by julien-c** [comment]
I would go with option 2 from @Wauplin, it seems reasonable to me

**Comment by Wauplin** [comment]
Fixed by a server-side update (private PR: https://github.com/huggingface/moon-landing/pull/6154)
