### ISSUE TITLE
Add `firstCreated` entry to `HfApi`

### ISSUE THREAD

**Issue by vvvm23** [huggingface/huggingface_hub#1481]
**Is your feature request related to a problem? Please describe.**
I would like `HfApi` to return information about the date when **a model, dataset or space was first created**.

**Describe the solution you'd like**
For example, after creating an API object using `api = HfApi()` I would like the following call to return a field named `firstCreated` or similar:
```python
In [8]: api.list_models()[0]
Out[8]:
ModelInfo: {
  {'_id': '621ffdc036468d709f174328',
   'author': None,
   'config': None,
   'downloads': 37086,
   'id': 'albert-base-v1',
   'lastModified': None,
   'firstCreated': <time string here> # <~~~~ new entry
   'likes': 1,
   'modelId': 'albert-base-v1',
   'pipeline_tag': 'fill-mask',
   'private': False,
   'securityStatus': None,
   'sha': None,
   'siblings': [],
   'tags': ['pytorch', 'tf', 'safetensors', 'albert', 'fill-mask', 'en', 'dataset:bookcorpus', 'dataset:wikipedia',
            'arxiv:1909.11942', 'transformers', 'exbert', 'license:apache-2.0', 'autotrain_compatible', 'has_space']}
}
```

**Describe alternatives you've considered**
I think you could probably use git to extract the time of the first commit, but it would be less clean than simply having this property.

**Additional context**
I basically want to have information about how many repositories there were at a given point in time.

**Comment by Wauplin** [comment]
Hi @vvvm23, if you want to get the datetime of the first commit of a repo you can use `HfApi.list_repo_commits` (see [docs](https://huggingface.co/docs/huggingface_hub/v0.14.1/en/package_reference/hf_api#huggingface_hub.HfApi.list_repo_commits). However we don't have a way to retrieve this information for all repos at a time (not with huggingface_hub nor the API) so you'll have to make 1 call per repo. Be careful not to do it too quickly otherwise you'll get rate limited. 

The reason why we don't have an official "created_at" field is that it's not easy to define/maintain especially if a repo git history is completely erased via a force push (+we don't have much demand for it)

**Comment by Wauplin** [comment]
I'll close this issue as "won't fix" for the reasons explained in https://github.com/huggingface/huggingface_hub/issues/1481#issuecomment-1556196114.
