### ISSUE TITLE
Endpoint interface for inpainting models that require two images.

### ISSUE THREAD

**Issue by OrderAndCh4oS** [huggingface/huggingface_hub#1486]
**Is your feature request related to a problem? Please describe.**
There doesn't appear to be an endpoint interface for Stable Diffusion inpainting models that require two image files, the base image and a mask. 

**Describe the solution you'd like**
It would be handy to have an interface for these models so that the Hosted inference API widget would work on the model card views. 

**Describe alternatives you've considered**
I recently had to create an endpoint for ControlNet inpainting: [OrderAndChaos/controlnet-inpaint-endpoint](https://huggingface.co/OrderAndChaos/controlnet-inpaint-endpoint). This was based on the [philschmid/stable-diffusion-2-inpainting-endpoint](https://huggingface.co/philschmid/stable-diffusion-2-inpainting-endpoint) endpoint.

**Comment by Wauplin** [comment]
Hi @OrderAndCh4oS , I think this issue should be addressed in https://github.com/huggingface/api-inference-community. If I understand correctly, you'd like to have a type of task supported right? More or less make https://huggingface.co/philschmid/stable-diffusion-2-inpainting-endpoint an "official" task? I think this should make sense only if there is a huge demand for it. Custom endpoints in Inference Endpoints are precisely made to handle more complex queries such as this one.

If you are looking for a way to demo your model, the best is to build a [Gradio app](https://gradio.app/docs/) and deploy it as [a Space](https://huggingface.co/spaces). Your model and your Space will automatically be linked so that users can test it.

**Comment by OrderAndCh4oS** [comment]
@Wauplin, thanks for the response. Totally fair. I believe this may be quite a common requirement for many stable diffusion models, so thought it worth asking anyway. I've moved the question to: https://github.com/huggingface/api-inference-community/issues/282.
