### ISSUE TITLE
Error to send model for evaluation “was not found on the hub!” 

### ISSUE THREAD

**Issue by brunotech** [huggingface/huggingface_hub#1500]
I trained a Falcon 7 model with a dataset of 300k Portuguese instructions called Caramelinho. I would like to add it to the Open LLM (Open Language Model) available at [Open LLM Leaderboard - a Hugging Face Space by HuggingFaceH4](https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard). However, every time I try to submit it for evaluation, I receive the following error: “Base model ‘Bruno/Caramelinho’ was not found on the hub!”

https://huggingface.co/Bruno/Caramelinho

I would like to know what I'm doing wrong when trying to add the model to the Open LLM.

![Captura de Tela_Área de Seleção_20230609023232](https://github.com/huggingface/huggingface_hub/assets/12931259/65633830-5575-485b-8638-ee37f66cb0dd)

**Comment by Wauplin** [comment]
Hi @brunotech, I don't know exactly what's the issue here. The best I can advice you to do is to create a discussion directly on the community tab of the Space: https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard/discussions. 

This repo is focused on the `huggingface_hub` library that powers all the libraries and apps communicating with the Hub. But in the case of the LLM leaderboard, I assume the issue comes from the implementation in that Space directly (most probably when trying to load the model with `AutoConfig` [here](https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard/blob/main/app.py#L227))

**Comment by Wauplin** [comment]
Closing the issue as no news for a few weeks (+ unrelated to `huggingface_hub`). Please reopen if needed.
