### ISSUE TITLE
error: failed to push some refs to 'https://user..' 

### ISSUE THREAD

**Issue by flckv** [huggingface/huggingface_hub#1560]
### Describe the bug

I finetuned a model and I have the output saved in a folder. I used `--push_to_hub` as usual and it worked so far with the same code but this time there was an error. 
So now I would like to upload from that folder.

- [ ] 1. Can you clarify how to replicate what the --push_to_hub does from the command line / python script? Is there a command to create the model card and upload only the files that --push_to_hub (without all checkpoints)?
- [ ] 2. How do I know what caused the issue of not uploading to the hub? How do I avoid it next time?

### Logs

```shell
This is the error message: 

Upload file pytorch_model.bin: 100%|█████████▉| 2.37G/2.37G [21:01<00:01, 3.87MB/s]
Upload file pytorch_model.bin: 2.38GB [21:02, 4.76MB/s]                            EOF
error: failed to push some refs to 'https://user:.....@huggingface.co/..../....'

07/12/2023 18:23:21 - WARNING - huggingface_hub.repository - EOF
error: failed to push some refs to 'https://user:.....@huggingface.co/..../....'


Upload file pytorch_model.bin: 100%|██████████| 2.37G/2.37G [21:03<00:00, 4.76MB/s]
Upload file pytorch_model.bin: 100%|██████████| 2.37G/2.37G [21:03<00:00, 2.02MB/s]
Traceback (most recent call last):
  File "/home/user/.conda/envs/de/lib/python3.11/site-packages/huggingface_hub/repository.py", line 1099, in git_push
    raise subprocess.CalledProcessError(return_code, process.args, output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'push', '--set-upstream', 'origin', 'main']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/l/users/user/a/script.py", line 460, in <module>
    main()
  File "/l/users/user/a/script.py", line 435, in main
    trainer.save_model()
  File "/home/user/.conda/envs/de/lib/python3.11/site-packages/transformers/trainer.py", line 2773, in save_model
    self.push_to_hub(commit_message="Model save")
  File "/home/user/.conda/envs/de/lib/python3.11/site-packages/transformers/trainer.py", line 3609, in push_to_hub
    git_head_commit_url = self.repo.push_to_hub(
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.conda/envs/de/lib/python3.11/site-packages/huggingface_hub/repository.py", line 1307, in push_to_hub
    return self.git_push(
           ^^^^^^^^^^^^^^
  File "/home/user/.conda/envs/de/lib/python3.11/site-packages/huggingface_hub/repository.py", line 1102, in git_push
    raise EnvironmentError(exc.stderr)
OSError: EOF
error: failed to push some refs to 'https://user:.....@huggingface.co/..../....'






The push command with PID 209317 failed.
07/12/2023 18:23:34 - ERROR - huggingface_hub.repository - The push command with PID 209317 failed.
EOF
error: failed to push some refs to 'https://user:.....@huggingface.co/..../....'

07/12/2023 18:23:34 - ERROR - huggingface_hub.repository - EOF
error: failed to push some refs to 'https://user:.....@huggingface.co/..../....''
```

### System info

```shell
huggingface-cli env

Copy-and-paste the text below in your GitHub issue.

- huggingface_hub version: 0.16.4
- Platform: Linux-5.4.199-ql-generic-12.0-18-x86_64-with-glibc2.31
- Python version: 3.11.4
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: /home/user/.cache/huggingface/token
- Has saved token ?: True
- Who am I ?: (ask me)
- Configured git credential helpers: store
- FastAI: N/A
- Tensorflow: N/A
- Torch: 2.0.1
- Jinja2: 3.1.2
- Graphviz: N/A
- Pydot: N/A
- Pillow: 9.4.0
- hf_transfer: N/A
- gradio: N/A
- tensorboard: N/A
- numpy: 1.24.4
- pydantic: 1.10.11
- aiohttp: 3.8.4
- ENDPOINT: https://huggingface.co
- HUGGINGFACE_HUB_CACHE: /home/user/.cache/huggingface/hub
- HUGGINGFACE_ASSETS_CACHE: /home/user/.cache/huggingface/assets
- HF_TOKEN_PATH: /home/user/.cache/huggingface/token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
```

**Comment by Wauplin** [comment]
Hi @flckv, I'm sorry you experienced this issue. I also saw [other comment in `transformers`](https://github.com/huggingface/transformers/issues/23187#issuecomment-1633489164). To be honest, I don't have a clear answer on why the error occured. It is most likely that the local git repo has somehow been corrupted. It can happen for different reasons:
- a commit has been pushed to the Hub (remote branch) and has not being pulled locally yet
- a file that is supposed to be pushed has LFS file is not properly tracked as LFS. Don't know how this could happen only with the training script.
- a file that is supposed to be pushed has being updated locally during the upload, resulting in a corrupted state
- other reasons I didn't think about

Overall, it all comes down to a local git management being the root cause of the problem. What I would do is to try to fix that outside of any Python script. Something like:

```sh
cd path/to/folder
git add .
git commit -m "Training results"
git pull  # potentially a git merge conflict to resolve here
git push
```
Doing a `git status` should also help.

If that doesn't work as expected, it is also possible to upload the output folder using HTTP methods. This can be achieve with [`upload_folder`](https://huggingface.co/docs/huggingface_hub/guides/upload#upload-a-folder) from the `huggingface_hub` library. It will not fix the problems with your local git repository but at least the files will be on the Hub.

---

Regarding _"Is there a command to create the model card and upload only the files that --push_to_hub (without all checkpoints)?"_ this is very `transformers`-specific and I'm not an expert here (cc @sgugger). The thing is, as long as we don't know what caused the issue it's quite hard to provide a workaround. Our goal is to move away from the current implementation that uses git commands under the hood to replace it with the `upload_folder` method that is Python-first, making it more robust and easier to investigate when a bug happens. In the meantime, I don't have a 100% bullet-proof solution :confused:

**Comment by sgugger** [comment]
You can do `trainer.create_model_card()` then manually upload the file `README.md` that will be created by it. As @Wauplin mentioned, we will move away from `upload_folder` in the near future.

**Comment by flckv** [comment]
hi, thank you for the guidance @Wauplin and @sgugger. From what I understand if the Readme.md is not created and pushed with` --push_to_hub`, then I have to manually create it : ( . 

I guess `trainer.create_model_card()` is rather an alternative to ` --push_to_hub` as it has to be called right after the training in the python script? 

I think I was trying to look for a more convenient method : D e.g.: a linux command to create a model card when I have everything else saved in the local directory after the training?

**Comment by julien-c** [comment]
> we will move away from `upload_folder` in the near future

you mean `move away to` no?

**Comment by sgugger** [comment]
Yes, move away from Repository to upload_folder, sorry.

**Comment by flckv** [comment]
thank you for the guidance @sgugger and correction @julien-c 

Indeed with upload_file() I got more meaningful error messages than with git when uploading a large 5GB + file 



1

from huggingface_hub import HfApi
from huggingface_hub import login
login(token="hf_….”)

```
api = HfApi()
api.upload_file(
    path_or_fileobj="/l/users/user/d/mydataset/mydataset.tar",
    path_in_repo="mydataset.tar",
    repo_id="user/mydataset",
    repo_type="dataset",
)
```

Two different error messages see: 



1. > ["ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2423)" ](https://gist.github.com/flckv/ff86ffc77407d4f9af4b8b12540b3431) 

-  see related issue: "[_@julien-c is right, it is a problem of DNS_](https://github.com/huggingface/transformers/issues/12575#issuecomment-1179170819 )" so  I tried to fix it with [these](https://stackoverflow.com/questions/33410577/python-requests-exceptions-sslerror-eof-occurred-in-violation-of-protocol ) installations without success



2. > ["huggingface_hub.utils._errors.BadRequestError: "](https://gist.github.com/flckv/2e608b117ab19d5a4fc150d03327f810)







2

```
pwd
/l/users/user/d/mydataset
ls
mydataset.tar

git status
On branch main
Your branch is ahead of 'origin/main' by 1 commit.
  (use "git push" to publish your local commits)

git add .
git commit -m "commit from user”
git push
```

Third error message see : 

> "EOF
> error: failed to push some refs to 'https://huggingface.co/datasets/user/mydataset'" 



Any suggestions on how to solve the upload models/datasets from cluster cli to hub issue based on these flagged errors?

**Comment by flckv** [comment]
Can it be that I downloaded and uploaded too much from/to the Hub that I reached some sort of limit? I am having issues with even downloading a model. I also have an issue right now when starting the training (dataset and model are already loaded into cache, and my Hub repo is cloned to the local directory, but the job on the cluster is killed)

**Comment by flckv** [comment]
I am not sure if this is related to this issue but I see that recently with some models the following files are not generated after the training finished: 

trainer_state.json
train_results.json
eval_results.json
README.md

**Comment by flckv** [comment]
now I am thinking that these issues might be because I am utilizing 2GPUs with deepspeed distributed setup?

**Comment by Wauplin** [comment]
@flckv it seems that you are having very different issues here so let's keep aside issues that are not related to HTTP problems. If you have issues with the Trainer script itself (not generating files, problem with distributed setup,...), it's best to open a separate issue for it (in `transformers` if that's where the problem comes from).

About the HTTP issue itself, are you running your machine behind a proxy? Or in a managed environment (school network, entreprise,...) that could affect your internet connection in some way? 

> Can it be that I downloaded and uploaded too much from/to the Hub that I reached some sort of limit?

We don't have such a limit on our side but it can be the case that your internet provider limited you in some way. Hard to tell without more information.

> path_or_fileobj="/l/users/user/d/mydataset/mydataset.tar",

Out of curiosity, is the `mydataset.tar` file a valid file. E.g. can you open it and confirm it is a valid tar archive?

**Comment by flckv** [comment]
thanks, @Wauplin, My workaround at the end was not to add `--push_to_hub` but to wait until my training was done and then manually push the generated files. 

What I noticed is that the `--push_to_hub` argument pushes the model file first and then generates these files:
[trainer_state.json
train_results.json
eval_results.json
README.md](https://github.com/huggingface/huggingface_hub/issues/1560#issuecomment-1635725592)

So when `--push_to_hub` fails then the above files are not generated.

**Comment by Wauplin** [comment]
Hey @flckv glad to know that your issues are mostly solved in the end.

@sgugger is it expected that results and readme are not generated if `--push-to-hub` is not passed? In any case, that seems to be a different issue if you want to continue the conversation in a separate issue in [transformers](https://github.com/huggingface/transformers) :)

**Comment by sgugger** [comment]
Yes this is expected for the model card. Like I said, you will have to manually call `trainer.create_model_card()`. For the others, it's not `Trainer`-related, this is something that depends on the training script you are actually running. They are generated after the line that tries to push to the Hub in our examples, so if your script errored there, it's jsut that the corresponding code was not executed.
