### ISSUE TITLE
some requests options like proxies and verify does not pass to model_info

### ISSUE THREAD

**Issue by wqh17101** [huggingface/huggingface_hub#1570]
### Describe the bug

https://github.com/huggingface/huggingface_hub/blob/2940a65b22e9552b0dd40f0b61f502f66896d46d/src/huggingface_hub/hf_api.py#L1692

some requests options like proxies and verify does not pass to `get`
We want
```
r = get_session().get(path, headers=headers, timeout=timeout, params=params,proxies=proxies,verify=False)
```

### System info

```shell
{'huggingface_hub version': '0.16.4', 'Platform': 'Windows-10-10.0.19044-SP0', 'Python version': '3.10.9'}
```

**Comment by Wauplin** [comment]
Hi @wqh17101, I don't think this is really a bug, more like a feature request since `model_info` doesn't even take proxy/verify as input.

We don't want to add http options such as `proxy` and `verify` in each and every method of `huggingface_hub`, which would be time-consuming to maintain for both us and third-party libraries maintainers. The other way to do this is to configure globally the `Session` object used to make requests. You can do this using [`configure_http_backend`](https://huggingface.co/docs/huggingface_hub/package_reference/utilities#huggingface_hub.configure_http_backend).

For example, to setup a proxy for each and every calls:

```py
import requests
from huggingface_hub import configure_http_backend, get_session

# Create a factory function that returns a Session with configured proxies
def backend_factory() -> requests.Session:
    session = requests.Session()
    session.proxies = {"http": "http://10.10.1.10:3128", "https": "https://10.10.1.11:1080"}
    return session

# Set it as the default session factory
configure_http_backend(backend_factory=backend_factory)
```

Once `configure_http_backend` is called, all the subsequent requests to the Hub will use your configuration :)

**Comment by wqh17101** [comment]
@Wauplin wow. It is really a good idea to use configure_http_backend. I will test it tomorrow. Thank you very much.

**Comment by Wauplin** [comment]
You're welcome :) Feel free to close the issue if everything works fine for you!

**Comment by wqh17101** [comment]
```
import requests
from huggingface_hub import configure_http_backend, snapshot_download, get_session


# Create a factory function that returns a Session with configured proxies
def backend_factory() -> requests.Session:
    session = requests.Session()
    session.proxies = {"http": "http://10.10.1.10:3128", "https": "https://10.10.1.11:1080"}
    session.verify = False
    return session


# Set it as the default session factory
configure_http_backend(backend_factory=backend_factory)
session = get_session()
snapshot_download(
    "meta-llama/Llama-2-13b-chat-hf",
    cache_dir="./cache1",
    local_dir="./Llama-2-13b-chat-hf1",
    token="xxxxx",
    proxies={"http": "http://10.10.1.10:3128", "https": "https://10.10.1.11:1080"}
)
```
it seems that nothing changed. Maybe my usage is wrong?

**Comment by wqh17101** [comment]
As i debug deeply, i found that the proxies in session will not affect the `get`.
Only `r = get_session().get(path, headers=headers, timeout=timeout, params=params,proxies=proxies)` can work.
I do not know whether this is a bug of requests?

**Comment by wqh17101** [comment]
https://github.com/psf/requests/issues/6488 You can see that this good idea above does not work well right now

**Comment by Wauplin** [comment]
@wqh17101 It seems that setting `proxy` on the `Session` object does work, or at least is meant to work since it's officially documented [here](https://requests.readthedocs.io/en/latest/user/advanced/#proxies). They do it this way:

```py
proxies = {
  'http': 'http://10.10.1.10:3128',
  'https': 'http://10.10.1.10:1080',
}
session = requests.Session()
session.proxies.update(proxies) # instead of `session.proxies = proxies`
```

However your issue might come from the order of priority when resolving the proxies. Here is what is stated [in the docs](https://requests.readthedocs.io/en/latest/user/advanced/#proxies):

> **Warning**
> Setting session.proxies may behave differently than expected. Values provided will be overwritten by environmental proxies (those returned by [urllib.request.getproxies](https://docs.python.org/3/library/urllib.request.html#urllib.request.getproxies)). To ensure the use of proxies in the presence of environmental proxies, explicitly specify the proxies argument on all individual requests as initially explained above.

A workaround suggested [in this stackoverflow thread](https://stackoverflow.com/questions/30837839/how-can-i-set-a-single-proxy-for-a-requests-session-object#comment86036962_30839005) is to set `session.trust_env = False` if you don't want your environment proxies to mess up with the ones you define. I guess this can have side effects on other configured values but I'm not knowledgeable on this.

Could you try that and keep me updated?

**Comment by wqh17101** [comment]
```
proxies = {
  'http': 'http://10.10.1.10:3128',
  'https': 'http://10.10.1.10:1080',
}
session = requests.Session()
session.proxies.update(proxies) # instead of `session.proxies = proxies`
```
can not work.


```
proxies = {
  'http': 'http://10.10.1.10:3128',
  'https': 'http://10.10.1.10:1080',
}
session = requests.Session()
session.trust_env = False
session.proxies.update(proxies) # instead of `session.proxies = proxies`
```
it worked!

**Comment by Wauplin** [comment]
Perfect, glad it solved your problem! I'll close this issue now but feel free to reopen if needed :)
