### ISSUE TITLE
Provide user manual download for "hf_hub_download " when "hf_hub_download" does not work

### ISSUE THREAD

**Issue by 2catycm** [huggingface/huggingface_hub#1572]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when "hf_hub_download" does not work. As you know, in many countries or regions, network connection are so strange that the python download tool can never see hugging face hub files, while user can always have other ways (wget, git clone, scp) to download the file properly. This makes users like me very confused, and we cannot enjoy the powerful open pretrained models/datasets and other resources elegantly, stepping away from hf toolchains.
**Describe the solution you'd like**
In Microsoft/vcpkg, which is a tool to download and install cmake dependencies, when something to be download does not work, the vcpkg will tell the user which url and which target disk location it is trying to download, then the user can utilize their own way to download that file. Running the tool again, the code would see the file is integral and continue to the next steps. I think this design is very execellent.
Now I am changing the codes of hugging face or other libraries that call  "hf_hub_download " to manually load the pytorch file that I've downloaded, because I have to use debug to see the parameters of hf_hub_download, and the cache of hf_hub_download  is not transparent, it changes over versions, I cannot fill the cache properly to make a successful download. 

**Describe alternatives you've considered**
solve the problem from the root:  why the requesting method that hf is using does not work, but git clone and wget work? for example, I can git clone from "https://huggingface.co/timm/swin_base_patch4_window7_224.ms_in22k_ft_in1k/tree/main", but I cannot call `cached_safe_file = hf_hub_download(repo_id='timm/swin_base_patch4_window7_224.ms_in22k_ft_in1k', filename='model.safetensors', revision=None)` .

**Additional context**

**Comment by Wauplin** [comment]
> the cache of hf_hub_download is not transparent, it changes over versions, I cannot fill the cache properly to make a successful download.

@2catycm I am sorry you are running into such issues. Changing the cache system would be difficult on our side as it is already widely used and is based on a particular structure and symlinks to efficient save disk space (see [cache explanation](https://huggingface.co/docs/huggingface_hub/guides/manage-cache)). I can assure that the cache system is not evolving over versions (it did once 18 months ago but has not changed ever since). That being said, it is true that for a given URL we know before-hand exactly where the file will be stored in the cache. Would it be helpful to you if a debug message is logged like `"Will download file from https://... and save it to 'path/to/disk'"` ? And if download fails you can always checks the logs to retrieve this exact message.

> for example, I can git clone from "https://huggingface.co/timm/swin_base_patch4_window7_224.ms_in22k_ft_in1k/tree/main", but I cannot call cached_safe_file = hf_hub_download(repo_id='timm/swin_base_patch4_window7_224.ms_in22k_ft_in1k', filename='model.safetensors', revision=None)

I'd be curious to know what error you are encountering here. What is the exact error? Could you copy-paste the stacktrace?

Just in case it might help, it is possible to pass `resume_download=True` to `hf_hub_download` (and many more HF-tools) which will check if you already tried to download the file and resume where it stopped. This might help you if you are struggling to download files.

**Comment by Wauplin** [comment]
Closing this issue as we've got no news for 6 weeks. Feel free to reopen if needed.
