### ISSUE TITLE
Commit not created when using HfApi.create_commit in ThreadPoolExecutor

### ISSUE THREAD

**Issue by narugo1992** [huggingface/huggingface_hub#1574]
### Describe the bug

As the title suggests, when using the `create_commit` method within a thread of the ThreadPoolExecutor, a commit is not created for the repository as expected.

But when I directly call the `upload_file` function in main thread, it's okay.

### Reproduction

```python
import logging
import os
from concurrent.futures import ThreadPoolExecutor
from tempfile import TemporaryDirectory

from huggingface_hub import HfApi, CommitOperationAdd

hf_client = HfApi(token=os.environ['HF_TOKEN'])


def upload_file():
    with TemporaryDirectory() as td:
        file = os.path.join(td, '1.txt')
        with open(file, 'w', encoding='utf-8') as f:
            f.write('2333')

        repo = 'narugo/test_commit_bug'
        hf_client.create_repo(repo, exist_ok=True, repo_type='dataset')

        hf_client.create_commit(
            repo_id=repo,
            repo_type='dataset',
            operations=[
                CommitOperationAdd(
                    path_or_fileobj=file,
                    path_in_repo='inner_1.txt',
                ),
            ],
            revision='main',
        )


if __name__ == '__main__':
    logging.basicConfig(level=logging.DEBUG)

    tp = ThreadPoolExecutor(max_workers=1)
    tp.submit(upload_file)

    tp.shutdown()

```

### Logs

This is the log output

```shell
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): huggingface.co:443
DEBUG:urllib3.connectionpool:https://huggingface.co:443 "POST /api/repos/create HTTP/1.1" 409 112
```

Clearly, huggingface_hub only performed the operation of creating the repository and did not create any commits at all.

### System info

```shell
- huggingface_hub version: 0.16.4
- Platform: Linux-5.15.0-76-generic-x86_64-with-glibc2.2.5
- Python version: 3.8.1
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: /home/narugo/.cache/huggingface/token
- Has saved token ?: True
- Who am I ?: Narugo
- Configured git credential helpers: 
- FastAI: N/A
- Tensorflow: N/A
- Torch: 2.0.1
- Jinja2: 3.1.2
- Graphviz: N/A
- Pydot: N/A
- Pillow: 9.5.0
- hf_transfer: N/A
- gradio: N/A
- tensorboard: N/A
- numpy: 1.24.4
- pydantic: N/A
- aiohttp: 3.8.5
- ENDPOINT: https://huggingface.co
- HUGGINGFACE_HUB_CACHE: /home/narugo/.cache/huggingface/hub
- HUGGINGFACE_ASSETS_CACHE: /home/narugo/.cache/huggingface/assets
- HF_TOKEN_PATH: /home/narugo/.cache/huggingface/token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
```

**Comment by Wauplin** [comment]
@narugo1992 I investigated it and it doesn't seem to be a bug in `huggingface_hub`. A few things about it:
- Exceptions raised in a task are caught. To retrieve it you must do `future = pool.submit(...)` => `future.result()`. The result is either the return value from the task or it raises the exception raised while executing the task. 
- In your case, the exception is `TypeError: HfApi.create_commit() missing 1 required keyword-only argument: 'commit_message'`.
- Finally, if you want a ThreadPoolExecutor of 1 worker, I would advice you to either run `create_commit(..., run_as_future=True)` which is doing exactly what you need. Otherwise another solution is to do 

```py
def upload_file():
    ...

future = hf_client.run_as_future(upload_file)
future.result()
```

This is similar to what you're doing but it uses a thread pool shared within the `HfApi` instance. Might be useful depending on your use case. [More info about run_as_future in this guide.](https://huggingface.co/docs/huggingface_hub/guides/upload#nonblocking-upload)

This should solve your bug. I'll close this issue but feel free to reopen if something's not clear :)
