### ISSUE TITLE
Impossible to download data with snapshot_download

### ISSUE THREAD

**Issue by sedol1339** [huggingface/huggingface_hub#1598]
### Describe the bug

I'm trying to download 253 parquet files with the following code:

```
from huggingface_hub import snapshot_download
snapshot_download(
      repo_id=f'mlfoundations/datacomp_medium',
      repo_type='dataset',
      allow_patterns='*.parquet',
      local_dir='medium',
      cache_dir='medium/hf_cache',
      local_dir_use_symlinks=False,
  )
```

In random moments one of the workers raises ConnectionError. So, I add parameter `resume_download=True` and wrap function call in `while True` with try-except inside (see reproduction code).

However, after each ConnectionError the function `snapshot_download` seems to start from scratch (progress bar shows 0/253 files). I guess that the whole progress gets lost. How to manage with this situation?

### Reproduction

```
from huggingface_hub import snapshot_download
while True:
    try:
        snapshot_download(
            repo_id=f'mlfoundations/datacomp_medium',
            repo_type='dataset',
            allow_patterns='*.parquet',
            local_dir='medium',
            cache_dir='medium/hf_cache',
            local_dir_use_symlinks=False,
            resume_download=True,
        )
        break
    except:
       pass
```

### System info

```shell
- huggingface_hub version: 0.16.4
- Platform: Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.27
- Python version: 3.9.17
- Running in iPython ?: Yes
- iPython shell: ZMQInteractiveShell
- Running in notebook ?: Yes
- Running in Google Colab ?: No
- Token path ?: /home/oleg/.cache/huggingface/token
- Has saved token ?: False
- Configured git credential helpers: 
- FastAI: N/A
- Tensorflow: N/A
- Torch: N/A
- Jinja2: 3.1.2
- Graphviz: N/A
- Pydot: N/A
- Pillow: 9.4.0
- hf_transfer: N/A
- gradio: N/A
- tensorboard: N/A
- numpy: 1.23.5
- pydantic: N/A
- aiohttp: N/A
- ENDPOINT: https://huggingface.co
- HUGGINGFACE_HUB_CACHE: /home/oleg/.cache/huggingface/hub
- HUGGINGFACE_ASSETS_CACHE: /home/oleg/.cache/huggingface/assets
- HF_TOKEN_PATH: /home/oleg/.cache/huggingface/token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
```

**Comment by Wauplin** [comment]
> However, after each ConnectionError the function snapshot_download seems to start from scratch (progress bar shows 0/253 files). I guess that the whole progress gets lost. How to manage with this situation?

Yes I understand that this is a bit counter-intuitive. The thing is that `snapshot_download` (download a repo) is built on top of `hf_hub_download` (download a single file). `hf_hub_download` is made in such a way that if the file is already cached locally, it will only do an http HEAD call to the Hub to check the file hasn't changed and directly return the cached  file (in the case it hasn't changed). What `snapshot_download` do is to list all the files to download and loop through them with a tqdm progress bar. That's why you see `0/253 files` again when it restarts. There is still a small delay per file but much less than if you were actually re-downloading the file.  

Does that make sense? In the end, the progress bar should show `0/253` but must be very fast at the beginning while it catches up the files that are already downloaded.

**Comment by WilliamChen-luckbob** [comment]
I have a similar issue. When using the `snapshot_download()` method for downloading, the program consistently gets disconnected. 

It's necessary to encapsulate it within a try-catch block and a loop; otherwise, the `snapshot_download()` method never succeeds in downloading the entire repository in one go. 

After a certain number of iterations of this loop for handling disconnected errors and re-downloading, it seems that the local files have the complete repository content. However, the download doesn't seem to conclude properly. I'm unsure whether the download has actually finished. Especially when training based on specific base models, it's often necessary to download the entire repository, and this snapshot_download() method appears to be malfunctioning.

Here is the code:
```
while True:
    try:
        snapshot_download("Meina/MeinaMix_V11", revision="main",
                          cache_dir="D:\\CodeRepository\\python-service\\huggingface_downloader\\temp_cache_dir",
                          local_dir="D:\\CodeRepository\\python-service\\huggingface_downloader\\local_dir",
                          token="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                          resume_download=True)
        break
    except Exception as e:
        print("error retry：" + str(e))
```

Indeed, this method becomes an infinite loop since the `snapshot_download()` function doesn't effectively verify the presence of existing files in `local_dir`, resulting in the process getting stuck and `temp_cache_dir` full of useless cache.

And how I fix this is just remove the `local_dir` param and get the result from cache file, and that works fine.

**Comment by blizzardwj** [comment]
"symlink" looks pretty decent, but what happens if I cp the whole model parameters to another device? Such as from Linux to Win.

**Comment by Wauplin** [comment]
@blizzardwj depends on how you make the cp. Most probably the whole file will be copy-pasted, losing the reference with the cache. But I'm not sure to see the use case (or see an alternative for that?)

**Comment by Wauplin** [comment]
> In random moments one of the workers raises ConnectionError. So, I add parameter resume_download=True and wrap function call in while True with try-except inside (see reproduction code).

> I have a similar issue. When using the snapshot_download() method for downloading, the program consistently gets disconnected.

@sedol1339 @WilliamChen-luckbob last update on this matter. I implemented and merged a built-in retry mechanism in the download process (see https://github.com/huggingface/huggingface_hub/pull/1766). What it does is to automatically resume the download as soon as a ConnectionError happens, without redownloading anything that is already downloaded. The patch will be shipped in the next release but in the meantime, you can install `huggingface_hub` [from source](https://huggingface.co/docs/huggingface_hub/installation#install-from-source) if you need it. Please let me know if you still encounter network issues. Hopefully, it should be definitely solved :)

**Comment by AndreiSoroka** [comment]
Just small proof, from huggingface_hub now is working
<img width="1448" alt="image" src="https://github.com/huggingface/huggingface_hub/assets/6079139/fa8e7099-f2a0-43c4-b607-0347da797d74">

**Comment by WilliamChen-luckbob** [comment]
Thanks alot, @Wauplin :
I've already resolved the issue differently by adjusting parameters to skip exceptions. Although the code is still raising some connection exceptions, it's acceptable to overlook them and retrieve the correct file from the cache directory. Here's my solution.
        ```
        from huggingface_hub import snapshot_download
        import argparse
        import logging

        # Press the green button to download the Hugging Face model from the Hugging Face Hub
        if __name__ == '__main__':
        # get command line arguments
            parser = argparse.ArgumentParser(description="downloading script ignoring exceptions")
        parser.add_argument("--repository_name", required=True, help="repository name")
        parser.add_argument("--cache_dir", required=False, help="cache file dir", default="./temp_cache_dir")
        parser.add_argument("--token", required=False, help="token", default="your auth code")
        args = parser.parse_args()

        # setting logger
        logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
        logger = logging.getLogger(__name__)

        # specify the cache_dir, otherwise it will be set to disc C by default and may blow your system disk
        # by default, set directory to current project root directory/temp_cache_dir
        cache_dir = args.cache_dir

        # specify the repository name
        repository_name = args.repository_name

        # specify a hugging face token
        token = args.token

        # using try catch + loop because the downloading will be failed thousands of times while downloading
        while True:
            try:
                # do not specify local_dir, it will always be failed in windows
                # just set like below is OK
                # after download, you can find the whole repository in cache_dir
                snapshot_download(repo_id=repository_name,
                                  revision="main",
                                  cache_dir=cache_dir,
                                  token=token,
                                  resume_download=True)
                logger.info(
                    "download success, check the repository " + cache_dir + " and your file shall be in [model_name]/snapshots/[temp_id]")
                break
            except Exception as e:
                logger.error("error retry：" + str(e))

        ```

**Comment by Wauplin** [comment]
> I've already resolved the issue differently by adjusting parameters to skip exceptions. Although the code is still raising some connection exceptions, it's acceptable to overlook them and retrieve the correct file from the cache directory. Here's my solution.

Your script is indeed valid. I'd be curious to know if you still need it now that the PR has been merged. Maybe you are facing more than 5 connection errors in a row? (and in this case, it fails and you need your retry-script).
