### ISSUE TITLE
load_dataset (model) behind proxy

### ISSUE THREAD

**Issue by DonnyWhoLovedBowling** [huggingface/huggingface_hub#1604]
**Is your feature request related to a problem? Please describe.**
At this point, the datasets.load_dataset(...) function takes a download_config parameter, which again supports a requests-type proxies configuration dictionary. However, when downloading dataset-info, the load_dataset function still malfunctions due to omittance of the use of this proxies-variable and the function crashes if you're behind a proxy.

**Describe the solution you'd like**
This function: [load_dataset](https://github.com/huggingface/huggingface_hub/blob/b9901bf71839850c10ea42162c69aecabc96a46b/src/huggingface_hub/hf_api.py#L1698C22-L1698C22) already uses a "token"-parameter, it could easily be expanded to also use the proxies-parameter. The function is only used at two separate instances at which the original download_config parameter is available and can therefore easily be adapted.

**Describe alternatives you've considered**
Probably there are alternatives: for example the whole download_config could be passed on as a full parameter.

**Additional context**
I think the same counts for the download_model function and maybe even other functions that use requests, this is not a comprehensive evaluation of alle places where "proxies" is not fully implemented.

**Comment by Wauplin** [comment]
(cc @lhoestq @albertvillanova from the `datasets` library)

Hey @DonnyWhoLovedBowling sorry for the late response, I'm getting back from holidays. Instead of adding new parameters for HTTP settings, the approach we promote in `huggingface_hub` is to globally configure the underlying `requests.Session` object using [`configure_http_backend`](https://huggingface.co/docs/huggingface_hub/v0.16.3/en/package_reference/utilities#huggingface_hub.configure_http_backend). To do so, you must add this snippet of code at the beginning of your script, before making HTTP calls:

```py
import requests
from huggingface_hub import configure_http_backend

# Create a factory function that returns a Session with configured proxies
def backend_factory() -> requests.Session:
    session = requests.Session()
    session.proxies = {"http": "http://10.10.1.10:3128", "https": "https://10.10.1.11:1080"}
    return session

# Set it as the default session factory
configure_http_backend(backend_factory=backend_factory)
```

This is a relatively new approach and we still need some time to propagate it to other libraries.

Please let me know if that solved your issue. If that's the case, feel free to close this issue :)

**Comment by lhoestq** [comment]
Note that `datasets` uses `aiohttp` for many features like streaming or downloading from the hub with `hf://` paths.

IIRC there is a HTTP_PROXY environment variable that you can use

**Comment by Wauplin** [comment]
Closing this issue as no news about the initial issues + the suggested solutions should work. Feel free to reopen if needed.
