### ISSUE TITLE
SSLError on huggingface API

### ISSUE THREAD

**Issue by narugo1992** [huggingface/huggingface_hub#1665]
### Describe the bug

We started noticing a large number of SSL errors (mainly `SSLEOFError` and `SSLZeroReturnError`) when accessing the `huggingface_hub` API about 30 hours ago, as shown in the log below (in UTC time):

We have tested this issue on servers in multiple locations (Beijing, Tokyo, LA), and the problem occurs consistently. It's unlikely to be a network issue on our end.

So, we would like to know the cause of this issue and how to resolve it. Additionally, until this problem is fixed, **what workarounds can we use to ensure that our project code can still run smoothly**?

### Reproduction

Easy to reproduce. All APIs can trigger this on our end.

### Logs

```shell
[09-15 02:50:37] WARNING  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLZeroReturnError(6, 'TLS/SSL connectionpool.py:823
                          connection has been closed (EOF) (_ssl.c:1131)'))': /api/datasets?author=CyberHarem
[09-15 02:50:39] WARNING  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLZeroReturnError(6, 'TLS/SSL connectionpool.py:823
                          connection has been closed (EOF) (_ssl.c:1131)'))': /api/datasets?author=CyberHarem
```

### System info

```shell
- huggingface_hub version: 0.16.4
- Platform: Linux-3.10.0-957.el7.x86_64-x86_64-with-glibc2.17
- Python version: 3.8.17
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: /nfs3/huggingface_models/token
- Has saved token ?: True
- Configured git credential helpers: 
- FastAI: N/A
- Tensorflow: N/A
- Torch: 2.0.1
- Jinja2: 3.1.2
- Graphviz: N/A
- Pydot: N/A
- Pillow: 9.5.0
- hf_transfer: N/A
- gradio: N/A
- tensorboard: N/A
- numpy: 1.24.4
- pydantic: N/A
- aiohttp: 3.8.5
- ENDPOINT: https://huggingface.co
- HUGGINGFACE_HUB_CACHE: /nfs3/huggingface_models/hub
- HUGGINGFACE_ASSETS_CACHE: /nfs3/huggingface_models/assets
- HF_TOKEN_PATH: /nfs3/huggingface_models/token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
```

**Comment by SID262000** [comment]
@narugo1992 Can you share the code snippet which results in the above issue, Thanks!

**Comment by Wauplin** [comment]
Hi @narugo1992, I'm sorry about the very late reply. And I'm sorry you're facing these issues. Our userbase is growing and we don't have much complains of this type lately so I'd be confident that this issue is happening less and less. We also made our upload and download process more robust to SSL errors lately which should help. However if you're still facing something similar, you can configure a custom retry mechanism yourself using `configure_http_backend` (see [reference](https://huggingface.co/docs/huggingface_hub/package_reference/utilities#huggingface_hub.configure_http_backend)). It is quite a power-user feature but I think your use case is also an advanced one right? (at least given the previous interactions we had :slightly_smiling_face:).

In the meantime, I will close this issue. Feel free to comment back if you are still facing the issue and I can reopen.
