### ISSUE TITLE
[Bug] Filtering models by tags using `ModelFilter` doesn't work

### ISSUE THREAD

**Issue by Wauplin** [huggingface/huggingface_hub#1668]
_Originally reported by @thomwolf on [Slack](https://huggingface.slack.com/archives/C02V5EA0A95/p1694703597439229) (private):_

Model filtering by tags using `ModelFilter` doesn't work:

```py
>>> from huggingface_hub import list_models, ModelFilter

>>> filter = ModelFilter(author="HuggingFaceBR4", tags=["tensorboard"])
>>> models = list(list_models(filter=filter))
>>> models[0]   # <= doesn't have a "tensorboard" tag
ModelInfo: { 
  {'_id': '63ff7c00ea1782e758c69b5d',
   'author': 'HuggingFaceBR4',
   'id': 'HuggingFaceBR4/gpt2-20b',
   (...)
   'tags': ['transformers', 'gpt2', 'text-generation', 'text-generation-inference', 'region:us']}
}
```

A workaround is to use `list_models(author="HuggingFaceBR4", filter="tensorboard")` directly without `ModelFilter`. Would still be good to investigate.

**Comment by martinbrose** [comment]
I shouldn't have closed my PR. @Wauplin, could you please reopen it?

The problem here is that the [`/api/models GET` endpoint](https://huggingface.co/docs/hub/api#endpoints-table) does not seem to have an additional parameter for tags.
It needs to be provided as part of the `"filter"` parameter, similar to the language filter, which is also just a language code within `ModelInfo.tags`. The original code erroneously provided the tags within `ModelFilter` as a `"tags"` parameter to the API endpoint.

**Comment by Wauplin** [comment]
Hi @martinbrose, thanks for investigating the bug and finding the cause! So this means the tags filter most probably never worked before :grimacing: I re-opened the PR you've created and will have a look at it soon.

**Comment by Wauplin** [comment]
> So maybe this functionality isn't really used anyway.

I think this is the key take-away! I've created https://github.com/huggingface/huggingface_hub/issues/1676 to definitely deprecate/remove those. We still need to find a way to do it without breaking too much stuff but it's definitely the direction we want to take.
