### ISSUE TITLE
snapshot_download does not support argument verify=False

### ISSUE THREAD

**Issue by samuelbaizg** [huggingface/huggingface_hub#1691]
Hello,  

when I set proxeis using huggingface_hub.snapshot_download to download models, I got the error "ConnectionResetError(54, 'Connection reset by peer')))".   Can you please add argument verify=False to the method of "snapshot_download" and pass the argument to python.Requests method to fix this issue ?

**Comment by Wauplin** [comment]
Hi @samuelbaizg, setting proxy can be done using the `HTTP_PROXY` and `HTTPS_PROXY` environment variables (see https://requests.readthedocs.io/en/latest/user/advanced/#proxies). Otherwise, it's possible to configure your own `requests.Session` object that will be reuse by `huggingface_hub` using [`configure_http_backend`](https://huggingface.co/docs/huggingface_hub/package_reference/utilities#huggingface_hub.configure_http_backend). Configuring your own Session gives you a fine-grained solution to set your own behavior instead of passing args like `verify=False` to every methods. Hope this will help you solve your issue.

**Comment by Wauplin** [comment]
Closing this issue as https://github.com/huggingface/huggingface_hub/issues/1691#issuecomment-1733259133 should fix it. Please let me know if you need further assistance :)
