### ISSUE TITLE
Adding the ability to configure etag timeout as env property 

### ISSUE THREAD

**Issue by Shahafgo** [huggingface/huggingface_hub#1703]
Hello HuggingFace Team!
I noticed that the etag_timeout in the snapshot_download request supports passing customized values but for some reason it was not in the pipeline and tokenizers of transformers and the timeout is set by default to 10 seconds without the ability to override and perhaps in another libraries as well.

This ability is important to me as I want to give the user the ability to configure the etag_timeout and because there is not an options to do so in tokenizer I have thought maybe it is a good idea to override the etag timeout for all the libraries (like in huggingface-cli) that use huggingface_hub.

**Comment by LysandreJik** [comment]
Hey @Shahafgo, thanks for your report! I think this makes sense!

@Wauplin should we move this report to `transformers` or would you like to keep it here and think of a library-agnostic way to handle this?

**Comment by Shahafgo** [comment]
Hi @Wauplin , I will do it shortly and I will opend a new pr.
I will update the issue once I finish, thank you for the quick response!

**Comment by Wauplin** [comment]
Great, looking forward for a PR! Thank you for raising the topic!

**Comment by Shahafgo** [comment]
@Wauplin @LysandreJik Hi team,
As part of my investigation, I can see that there is a timeout both for the head and the get requests of a file.
I think maybe it's a good idea to give the option to control both the timeout params.
In my opinion it's make sense, get requests maybe slow until getting the stream.
What do you think?

**Comment by Wauplin** [comment]
@Shahafgo those 2 timeouts are indeed pretty different. I think it's already the case the the timeouts have different values (10s for the HEAD and 60s or the GET if I remember correctly). However I would not add another parameter for the GET call. I think it's fine enough with the default value. Here is my reasoning:

The "why etag_timeout is more important to configure" is that in the case the model weights are already cached, we are still doing a HEAD call to the Hub to check the model has not being updated since we cached it. This HEAD call is important to stay up to date but not mandatory: if it fails we default back to the cached files. So reducing the HEAD call timeout would definitely help on slow connections when the files are already cached and we don't want to wait before loading them. On the contrary if the GET request is triggered, we **need** this call to work. If it doesn't, there is no fallback and the script fails with a TimeoutError. So setting a high value (60s) for the timeout should be good. Also this timeout period is in any case expected to be faster than the download time itself.

What I'm afraid of as well is if we have a `$HF_HUB_GET_TIMEOUT` one would expect it to be a timeout on _any_ GET requests we make to the Hub (download weights but also listing models, getting model files,...). I would prefer just not introducing it so that we don't have to handle it ^^

What do you think? Would also be interested in @LysandreJik's opinion here in case I missed something with these timeout settings.

**Comment by LysandreJik** [comment]
Your analysis sounds good to me @Wauplin

**Comment by Wauplin** [comment]
Ok thanks, then let's keep only a `$HF_HUB_ETAG_TIMEOUT` as described in https://github.com/huggingface/huggingface_hub/issues/1703#issuecomment-1742591995. @Shahafgo please let me know if you want to open a PR for that change :)

**Comment by Shahafgo** [comment]
@Wauplin @LysandreJik, guys I don׳t know how to thank you for the explanation, I appreciate it.
I am changing the code now and I will send the PR here once I am done, It will not take longer than a day.

**Comment by Wauplin** [comment]
> Also I took a look on the code and it seems that the http_get function has 10 seconds timeout by default.

Correct. My apologies, I thought it was way higher than this. Then yes it makes sense for the user to be able to increase this value. What do you think of `$HF_HUB_DOWNLOAD_TIMEOUT`? That way it would not be confused with the other GET methods in `HfApi`.

**Comment by Shahafgo** [comment]
Ok thank you, I will make the recent wanted changes and I will open the pr.

**Comment by Shahafgo** [comment]
@Wauplin @LysandreJik This is the pr : https://github.com/huggingface/huggingface_hub/pull/1720
Please let me know if something should be changed or should be added.

**Comment by Wauplin** [comment]
Reviewed the PR! Thanks for the good job :tada:

**Comment by Shahafgo** [comment]
@Wauplin Thank you for your review!
I am a bit confused and I would to discuss about it.
First, It seems like http_get uses the as well _request_wrapper.
So according to your suggestion above and at the bottom.
The timeout in http_get should be set according HF_HUB_DOWNLOAD_TIMEOUT
The timeout in _request_wrapper should be set according HF_HUB_ETAG_TIMEOUT
So if both will be set the HF_HUB_ETAG_TIMEOUT in _request_wrapper will override the HF_HUB_DOWNLOAD_TIMEOUT.
Maybe we should use only one variable in _request_wrapper, lets say HF_HUB_REQUEST_TIMEOUT and thats all?

**Comment by Wauplin** [comment]
> First, It seems like http_get uses the as well _request_wrapper.
So according to your suggestion above and at the bottom.
The timeout in http_get should be set according HF_HUB_DOWNLOAD_TIMEOUT
The timeout in _request_wrapper should be set according HF_HUB_ETAG_TIMEOUT
So if both will be set the HF_HUB_ETAG_TIMEOUT in _request_wrapper will override the HF_HUB_DOWNLOAD_TIMEOUT.
Maybe we should use only one variable in _request_wrapper, lets say HF_HUB_REQUEST_TIMEOUT and thats all?

Sorry for the confusion!

What I wanted to say is that for each value (etag timeout and download timeout) we should check the set value against the default value only in 1 place which will be:
- `http_get` for `HF_HUB_DOWNLOAD_TIMEOUT` (as done [here](https://github.com/Shahafgo/huggingface_hub/blob/b799b004b0d6a0ea93e7686d31bfa7fd80c5270a/src/huggingface_hub/file_download.py#L493))
- `file_download.hf_hub_download` for `HF_HUB_ETAG_TIMEOUT` (as done [here](https://github.com/Shahafgo/huggingface_hub/blob/b799b004b0d6a0ea93e7686d31bfa7fd80c5270a/src/huggingface_hub/file_download.py#L1154))

And nothing to check in `_request_wrapper`, that was my mistake!
So it seems all good to me. I'll make a last review and we're good to go :)

**Comment by Wauplin** [comment]
And... merged! (https://github.com/huggingface/huggingface_hub/pull/1720) :rocket: Nice contribution @Shahafgo :hugs:

**Comment by Shahafgo** [comment]
@Wauplin , I was in the middle of my work! It will not work! revert the changes!
