### ISSUE TITLE
Git LFS fails to fetch files from git@hf.co with SSH auth

### ISSUE THREAD

**Issue by antony-frolov** [huggingface/huggingface_hub#1706]
### Describe the bug

Getting
```
batch response: Authentication required: Password authentication in git is no longer supported. You must use a user access token or an SSH key instead. See https://huggingface.co/blog/password-git-deprecation
Failed to fetch some objects from 'https://hf.co/mistralai/Mistral-7B-v0.1.git/info/lfs'
```
when trying to `git lfs pull` on a repository pulled with `git clone git@hf.co:mistralai/Mistral-7B-v0.1`

`ssh -T git@hf.co` works fine

### System info

```shell
- huggingface_hub version: 0.17.3
- Platform: Linux-5.4.111-14-x86_64-with-glibc2.27
- Python version: 3.10.11
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: /home/lovanto/.cache/huggingface/token
- Has saved token ?: False
- Configured git credential helpers:
- FastAI: N/A
- Tensorflow: N/A
- Torch: 2.0.1
- Jinja2: 3.1.2
- Graphviz: N/A
- Pydot: N/A
- Pillow: 9.4.0
- hf_transfer: N/A
- gradio: N/A
- tensorboard: N/A
- numpy: 1.24.3
- pydantic: N/A
- aiohttp: N/A
- ENDPOINT: https://huggingface.co
- HUGGINGFACE_HUB_CACHE: /home/lovanto/.cache/huggingface/hub
- HUGGINGFACE_ASSETS_CACHE: /home/lovanto/.cache/huggingface/assets
- HF_TOKEN_PATH: /home/lovanto/.cache/huggingface/token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
```

**Comment by Wauplin** [comment]
Hi @antony-frolov, we have deprecated the use of passwords to authenticate with git (see related [blog post](https://huggingface.co/blog/password-git-deprecation)). Deprecation cycle ended yesterday and the change is in effect since a few hours ago. Therefore I assume the problem comes from a configuration issue. Let's find out what it is. What is the output of
```
git remote get-url origin
```
in your cloned repository?

**Comment by antony-frolov** [comment]
Hi @Wauplin! The output is `git@hf.co:mistralai/Mistral-7B-v0.1`

**Comment by Wauplin** [comment]
@antony-frolov I triggered an internal issue about that and the issue seems to come from our side. My apologies about the inconvenience it created. We've now reverted the auth deprecation until we fix the issue server-side. So in the meantime you should be able to `git lfs pull` correctly. Can you confirm?

**Comment by Wauplin** [comment]
Closing this issue as the issue has been fixed server-side. Please let me know if you still encounter a problem. And thanks for reporting in the first place!

**Comment by julien-c** [comment]
cool glad to hear @antony-frolov!

**Comment by zhangchunsheng** [comment]
git lfs pull                         
batch response: Authentication required: Password authentication in git is no longer supported. You must use a user access token or an SSH key instead. See https://huggingface.co/blog/password-git-deprecation
