### ISSUE TITLE
Docs request: `InferenceClient.post`

### ISSUE THREAD

**Issue by jamesbraza** [huggingface/huggingface_hub#1730]
https://huggingface.co/docs/huggingface_hub/main/en/package_reference/inference_client#huggingface_hub.InferenceClient.post

I would like to request we expand the docs on `InferenceClient.post`:
- `json`/`data`: link where one can read about what to put into the JSON blob
- `task`: link where to find all possible task names

**Comment by Wauplin** [comment]
Hi, yes indeed we could improve that :)

> json/data: link where one can read about what to put into the JSON blob

Are you thinking about something like that for example: https://requests.readthedocs.io/en/latest/user/quickstart/#more-complicated-post-requests

> task: link where to find all possible task names

Complete task list can be found on https://huggingface.co/tasks

> I would like to request we expand the docs on InferenceClient.post:

Would you like to open a quick PR for that? You just have to update the docstring of [`InferenceClient.post`](https://github.com/huggingface/huggingface_hub/blob/0cf0c9fff9570e831090b0075b50749958728a50/src/huggingface_hub/inference/_client.py#L181). Then you need to run `make style` to copy the docstring directly to the auto-generated `AsyncInferenceClient.post`.

**Comment by Wauplin** [comment]
> For the JSON blob, I more meant the schema of the blob, not how to send one. Like is there a JSON schema or Swagger docs for the JSON blob to pass to InferenceClient.post?

`InferenceClient.post` is meant to run inference on an arbitrary API (so the task you want). Therefore there is no predefined swagger schema since it depends on the endpoint you are using. But what I can tell you is that all tasks supported by InferenceAPI and Inference Endpoints are supported by the other methods so you shouldn't need to use `.post` except for an advanced use case.

If you want to know more about the parameter for InferenceAPI you can check out [this doc page](https://huggingface.co/docs/api-inference/detailed_parameters).

**Comment by jamesbraza** [comment]
Okay thank you!  Going to close this out, knowledge is in https://github.com/huggingface/huggingface_hub/pull/1740
