### ISSUE TITLE
Docs request: what is loaded/loadable?

### ISSUE THREAD

**Issue by jamesbraza** [huggingface/huggingface_hub#1734]
When working with `get_model_status`: https://huggingface.co/docs/huggingface_hub/main/en/package_reference/inference_client#huggingface_hub.InferenceClient.get_model_status

It tells you if the model is loadable and/or loaded.  The question is, what does this mean?
- What does "loaded" mean... what is it loaded into?
- If something isn't loaded, but is loadable, how can one load it?

**Comment by Wauplin** [comment]
Hey there, so I agree we could be more specific.
First of all, `get_model_status` is only applicable to InferenceAPI which is the hosted service we offer for quick prototyping. It is not meant for a production usage but it's very handy when it comes to trying models. For more details, check out [these docs](https://huggingface.co/docs/api-inference/index).

> What does "loaded" mean... what is it loaded into?

Models are not always loaded and served by our infra. That would be a huge waste of hardware and money for very little outcome for the community. Instead of that, models are loaded on the server on demand. So "loaded" just means that the model is instantly ready to use.

> If something isn't loaded, but is loadable, how can one load it?

"loadable" means that the model is currently not served but can be if you make a request to the endpoint. On the first request, you will have to wait for the server to load the model (cold start). You can request to load any "loadable" model (i.e. model not too big + with a supported library), even if you don't own them on the Hub.

If you have more question, check out the FAQ: https://huggingface.co/docs/api-inference/faq.

Does that answer your question? Would you mind opening a PR to add this information to the docstring (or at least explain in one sentence each possible status?).

**Comment by jamesbraza** [comment]
Okay thank you for the answers, I opened a draft PR.  One question is, why is `ModelStatus` return not being auto-linked in the docstring for https://huggingface.co/docs/huggingface_hub/main/en/package_reference/inference_client#huggingface_hub.InferenceClient.get_model_status? I can see `InferenceClient` is being autolinked

**Comment by Wauplin** [comment]
> One question is, why is ModelStatus return not being auto-linked in the docstring for https://huggingface.co/docs/huggingface_hub/main/en/package_reference/inference_client#huggingface_hub.InferenceClient.get_model_status?

Nice finding! I fixed it in the PR you've opened (see https://github.com/huggingface/huggingface_hub/pull/1740#issuecomment-1763952537).

**Comment by Wauplin** [comment]
Yes sorry about that. All good now.
For next time, what I usually do in these cases is to pull the changes locally, resolve a merge conflict and then push (instead of force pushing). Though it's not always easy depending on the changes.
