### ISSUE TITLE
`from_pretrained_keras` - add model path

### ISSUE THREAD

**Issue by innat** [huggingface/huggingface_hub#1744]
**Is your feature request related to a problem? Please describe.**
I have uploaded several video-mae checkpoints (SavedModel format) to huggingfacae-model hub, [LINK](https://huggingface.co/innat/videomae/tree/main). There are total 10+ checkpoints of videomae model. Instead of uploading them separately, I preferred this way.  The problem seems arise while trying to get them using [`from_pretrained_keras`](https://github.com/huggingface/huggingface_hub/blob/209c1ea652c33af0e902466ef7c209201082a337/src/huggingface_hub/keras_mixin.py#L217) method. 

I tried as follows but 

```python
model = from_pretrained_keras(
   "innat/videomae/TFVideoMAE_S_SSv2_16x224_FT"
)
```

```bash
HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'innat/videomae/TFVideoMAE_S_SSv2_16x224_FT'. Use `repo_type` argument if needed.
```

Seems like it expects the following format and also single model's file in one model repo.

```python
model = from_pretrained_keras(
   "innat/videomae"
)
```

I quickly check the doc if I could do this `innat/videomae/TFVideoMAE_S_SSv2_16x224_FT` but didn't find any source.

**Comment by Wauplin** [comment]
Hi @innat, there is indeed no built-in way to achieve what you are doing as the general guidance is usually "1 repo = 1 model". This . I can suggest you a few options here:

**1. Stick to 1 repo = 1 model and build a Collection**

With 1 repo = 1 model, you will be able to use `from_pretrained_keras` out of the box. It can enable some other features from the hub like the inference widget, the download counter,... (in your specific case, video-classification is not yet supported by inference widget). If you do that, you'll end up with ~13 repos that you can then group in a [Collection](https://huggingface.co/docs/hub/collections). The advantage of the collection is that you can shortly document to your users what is the difference between each checkpoint.

Caveat: to do this, you'll have to reupload the checkpoints you've already uploaded.

**2. Use single repo but 1 model == 1 branch**

Another possibility if you really don't want to have different repos is to create git branches for each checkpoint. Then, you can load them using `from_pretrained_keras(..., revision="TFVideoMAE_B_SSv2_16x224_FT")`. Make sure to document the repo correctly to let your users know about the different branches.

Here are a few resources helpful if you want to create those automatically:
- [create branches](https://huggingface.co/docs/huggingface_hub/guides/repository#branches-and-tags)
- [copy files](https://huggingface.co/docs/huggingface_hub/guides/upload#createcommit) (copy from main branch to new branches to avoid upload process)

**3. Keep repo structure but customize loading**

Another option is to keep your existing repo but write some logic to load the model correctly. To do so, I would 1) download the wanted folder 2) provide a path to `from_pretrained_keras` instead of a repo_id.

```py
# download only subfolder
cache_path = snapshot_download(repo_id="innat/videomae", include_patterns="TFVideoMAE_B_SSv2_16x224_FT/*")

# Load from cache
model = from_pretrained_keras(os.path.join(cache_path, "TFVideoMAE_B_SSv2_16x224_FT"))
```

---

In general I would be more in favor of solution 1. to clearly define that you have several checkpoints of the same model architecture. Otherwise if you are building your own library/scripts maybe solution 3. is enough.

cc @osanseviero @julien-c who might have different ideas on how to handle this

**Comment by julien-c** [comment]
Great writeup by @Wauplin and I agree 1. would be the best!

**Comment by innat** [comment]
Thanks @Wauplin for such detail write up. For now, I might go with option 3 if needed. However,  would it be align with the [HF APIs](https://github.com/huggingface/huggingface_hub/blob/209c1ea652c33af0e902466ef7c209201082a337/src/huggingface_hub/file_download.py#L1004) to update the `from_pretrained_keras` as follows. 

```python
model = from_pretrained_keras(
   repo_id  = ?, 
   filepath = ?,
)
where,
repo_id = "innat/videomae"
filepath = "TFVideoMAE_S_SSv2_16x224_FT"
```

**Comment by Wauplin** [comment]
> However, would it be align with the [HF APIs](https://github.com/huggingface/huggingface_hub/blob/209c1ea652c33af0e902466ef7c209201082a337/src/huggingface_hub/file_download.py#L1004) to update the from_pretrained_keras as follows.

I am not sure to understand the question.

[`from_pretrained_keras`](https://github.com/huggingface/huggingface_hub/blob/99040ecbb8fe6fad2fd19498fa033638968d1b21/src/huggingface_hub/keras_mixin.py#L217) takes as input a single parameter `pretrained_model_name_or_path`. Instead of providing a repo_id ("innat/videomae") you will have to pass the output of `snapshot_download` (i.e. `os.path.join(snapshot_download(repo_id="innat/videomae", include_patterns="TFVideoMAE_B_SSv2_16x224_FT/*"), "TFVideoMAE_B_SSv2_16x224_FT")`).

**Comment by innat** [comment]
A possible feature request for [from_pretrained_keras](https://github.com/huggingface/huggingface_hub/blob/99040ecbb8fe6fad2fd19498fa033638968d1b21/src/huggingface_hub/keras_mixin.py#L217).

Here [`hf_hub_download`](https://github.com/huggingface/huggingface_hub/blob/209c1ea652c33af0e902466ef7c209201082a337/src/huggingface_hub/file_download.py#L1005-L1006), it takes repo id and a filename in that repo. If same is supported in `from_pretrained_keras` api, hopefully it would be possible to do as follows, no!

```
model = from_pretrained_keras(
   repo_id  = ?, 
   filepath = ?,
)
where,
repo_id = "innat/videomae"
filepath = "TFVideoMAE_S_SSv2_16x224_FT"
```

**Comment by Wauplin** [comment]
Yes indeed so `"TFVideoMAE_S_SSv2_16x224_FT"` would be more of a `folder_path` rather than `filepath` right? It would require to add a `include_patterns` argument to snapshot_download (not `hf_hub_download`) and then load from the model from the subfolder.

But as said in https://github.com/huggingface/huggingface_hub/issues/1744#issuecomment-1764104115, we tend to promote solution 1) as the go-to solution is the case of multiple models sharing the same architecture. So I don't think we will add such a new feature in `from_pretrained_keras` for now since it would be promoting the opposite solution.
