### ISSUE TITLE
Support passing config as dataclass in `ModelHubMixin`

### ISSUE THREAD

**Issue by NielsRogge** [huggingface/huggingface_hub#1750]
**Is your feature request related to a problem? Please describe.**

I'm currently integrating the [PyTorchModelHubMixin](https://huggingface.co/docs/huggingface_hub/package_reference/mixins) class  into various Github repositories to showcase its convenience. This mixin's `push_to_hub` method supports a `config` argument, which then automatically gets saved as a config.json. This is great to store all kinds of hyperparameters related to the model's architecture.

It'd be great to, when reloading a model using the `from_pretrained` method, to have access to the various fields as Python attributes, e.g. `config.vocab_size`. 

Currently, let's say I have a class that looks like this:

```py
from dataclasses import dataclass, asdict

import torch
import torch.nn as nn
from huggingface_hub import PyTorchModelHubMixin


@dataclass
class Config:
    hidden_size: int = 512
    vocab_size: int = 30000


class MyModel(nn.Module, PyTorchModelHubMixin):
    def __init__(self, config):
        super().__init__()
        self.param = nn.Parameter(torch.rand(config.hidden_size, config.vocab_size))
        self.linear = nn.Linear(4, 5)

    def forward(self, x):
        return self.linear(x + self.param)
```

Then I can load and push it as follows:

```py
config = Config()
model = Transformer(config)

model.push_to_hub("nielsr/my-model", config=asdict(config))
```

However, when reloading like so:

```py
reloaded_model = MyModel.from_pretrained("nielsr/my-model")
````

then it fails with:

```py
AttributeError: 'dict' object has no attribute 'hidden_size'
```
This was encountered for https://github.com/mlfoundations/open_lm/pull/20.

**Describe the solution you'd like**

I have 2 feature requests:

- would it be possible to automatically push the config as a config.json to the hub, similar to how it's done in HF Transformers? This way, one doesn't need to pass the `config` when calling push_to_hub.
- it would be great to have access to the config attributes using `config.vocab_size` etc. when using `from_pretrained`, similar to HF Transformers

**Comment by Wauplin** [comment]
Looks reasonable to me. Thanks for opening the issue @NielsRogge :+1: I'll have to dive back into the implementation to check how to do that in a convenient background-compatible way.

**Comment by osanseviero** [comment]
Great idea! This would also unlock download stats for these projects as we use `config.json` to count downloads

**Comment by Wauplin** [comment]
Hey there :wave: So I looked into the existing code and it seems that we are already not far from it.

> 1. would it be possible to automatically push the config as a config.json to the hub, similar to how it's done in HF Transformers?

Yes. This is already done automatically [here](https://github.com/huggingface/huggingface_hub/blob/3a9919966391f7fd91066fe760c11bb5ea5059e5/src/huggingface_hub/hub_mixin.py#L64).

> 1.b. This way, one doesn't need to pass the config when calling push_to_hub.

We still need to pass it to `.push_to_hub` as we _have to_ get it from somewhere.

> 2. it would be great to have access to the config attributes using `config.vocab_size` etc. when using `from_pretrained`, similar to HF Transformers

Can you point me where is it done in `transformers`? I've seen Config objects defined in the `examples/` folder (like [here](https://github.com/huggingface/transformers/blob/c030fc891395d11249046e36b9e0219685b33399/examples/research_projects/lxmert/utils.py#L106)) but never has an official feature. And I'd prefer not to add this as an official object (I find it to be a pretty ugly mix between dicts and dataclasses). 

---

That being said, I am still undecided on if we should add more support for config in `PyTorchModelHubMixin`. To sum up, at the moment:
1. `config={...}` can be passed to `push_to_hub` which saves it as a config.json file on the Hub. Quite practical to count downloads afterwards.
2. if a config file exists in the repo, `config={...}` is passed to `__init__` as a dictionary

**What we could do** (only a suggestion):
1. when saving with `push_to_hub` or `save_pretrained`:
    1. if `config` is passed as a dict => we serialize it as config.json (current behavior)
    2. if `config` is passed as a dataclass => we serialize it as config.json (avoid the explicit `asdict` from user)
    3. if `config` is passed as something else => we try to `json.dump` but most probably it'll fail (not our problem)
    4. if `config` is not passed but `MyModel.config` exists and is a dict => serialize it
    5. if `config` is not passed but `MyModel.config` exists and is a dataclass => serialize it
    6. if `config` is not passed but `MyModel.config` exists and is something else => serialize it but maybe it'll fail
2. when loading the model with `_from_pretrained` we inspect the `MyModel.__init__` signature and especially the `config` parameter:
    1. either `config` is not a parameter => we don't pass the config
    3. either `config` exists and is typed as `dict` => we pass config as a dict (current behavior)
    9. either, `config` exists and is typed as a `dataclass` => we pass config as the dataclass
    10. either, `config` exists and is typed as something else => we pass config as a dict since we don't "understand" the expected type
    11. either, `config` exists and is not typed => we pass config as a dict

WDYT @NielsRogge @osanseviero? Does it seem reasonable to you?
In general, I'd like to add features but only if they are optional and not too opinionated. That's why I'd prefer to rely on dict and dataclasses only but nothing fancier than this.

**Comment by NielsRogge** [comment]
This looks good to me!
