### ISSUE TITLE
Model "xxx" was not found on hub!

### ISSUE THREAD

**Issue by zyh3826** [huggingface/huggingface_hub#1794]
### Describe the bug

I use git to push my model to the hub, [my model](https://huggingface.co/zyh3826/llama2-13b-ft-openllm-leaderboard-v1)
it can be seen on the web, but when I submit it to the [Leaderboard](https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard), this error happened:
![image](https://github.com/huggingface/huggingface_hub/assets/31238754/570ee69d-464b-4ed6-a267-e36732784322)
and I try it this way:
```python
from transformers import AutoConfig, AutoModel, AutoTokenizer
save_dir = 'zyh3826/llama2-13b-ft-openllm-leaderboard-v1'
config = AutoConfig.from_pretrained(save_dir)
tokenizer = AutoTokenizer.from_pretrained(save_dir)
```
everything is ok
<img width="1727" alt="企业微信截图_5dda03f8-18f3-468a-8a37-60bf433067ba" src="https://github.com/huggingface/huggingface_hub/assets/31238754/1cde9c1b-7270-4247-8ee7-0a0075810242">

anyone can help me? thanks a lot

### Reproduction

submit it on the openllm leaderboard

### Logs

```shell
Model "zyh3826/llama2-13b-ft-openllm-leaderboard-v1" was not found on hub!
```

### System info

```shell
None
```

**Comment by Wauplin** [comment]
Hey @zyh3826 , this issue seems to be related to the Open LLM Leaderboard, not the `huggingface_hub` library itself. It would be better to open a discussion directly on the Space community tab ([here](https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard/discussions)).

Regarding the issue, I think it is because [your model](https://huggingface.co/zyh3826/llama2-13b-ft-openllm-leaderboard-v1) is gated, meaning users have to accept the license to download the model. So the Open LLM Leaderboard cannot evaluate it properly. Maybe a more explicitly error message would be better though (cc @clefourrier)

**Comment by zyh3826** [comment]
> Hey @zyh3826 , this issue seems to be related to the Open LLM Leaderboard, not the `huggingface_hub` library itself. It would be better to open a discussion directly on the Space community tab ([here](https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard/discussions)).
> 
> Regarding the issue, I think it is because [your model](https://huggingface.co/zyh3826/llama2-13b-ft-openllm-leaderboard-v1) is gated, meaning users have to accept the license to download the model. So the Open LLM Leaderboard cannot evaluate it properly. Maybe a more explicitly error message would be better though (cc @clefourrier)

thanks for your reply @Wauplin  , I will check the gate

**Comment by clefourrier** [comment]
Closing since an[ issue](https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard/discussions/347) was also opened on the Leaderboard.
@Wauplin good intuition, it is indeed because the base model is gated

**Comment by Wauplin** [comment]
Thanks for taking care of it @clefourrier !

**Comment by julien-c** [comment]
question was also posted in the Forums. Please do not post same question to multiple channels @zyh3826, thanks!
