### ISSUE TITLE
Rename CLI to hf or at least put an alias on it

### ISSUE THREAD

**Issue by remyleone** [huggingface/huggingface_hub#1812]
**Is your feature request related to a problem? Please describe.**

It is frustrating to type "hugg" and then type tab to have the completion appear.
Could you offer when the installation is a `brew install huggingface-cli` a way to have an alias on `hf`

**Describe the solution you'd like**

`hf login`
`hf whoami`

**Describe alternatives you've considered**

Making an alias

**Additional context**

This is very similar to the github CLI that is just `gh` https://cli.github.com/

**Comment by julien-c** [comment]
yes, is there a way to define an alias in brew? what about in other package managers?

(I assume defining the alias in the Python library directly would not work on most systems)

**Comment by Wauplin** [comment]
> is there a way to define an alias in brew? what about in other package managers?

Ping @singingwolfboy who created the brew package (thanks again :pray:). 

Having a `hf` alias would be nice. The reason why we don't want to make it the default name is that it is already used by other tools like [this one](https://docs.humanfirst.ai/docs/cli/overview/), [this one](https://github.com/sorairolake/hf) and [this one](https://github.com/hugows/hf) (and maybe others). Having our own `huggingface-cli` name is longer to type (autocompletion helps) but at least it is explicit/self-explanatory.

**Comment by singingwolfboy** [comment]
The right way to solve this problem is to define an alias in your shell. Here are two articles I found with some instructions on how to do that: [aliases in bash](https://www.digitalocean.com/community/tutorials/an-introduction-to-useful-bash-aliases-and-functions), [aliases in zsh](https://adamtheautomator.com/zsh-alias/). Basically, you need to edit your shell configuration file and add this line:

```bash
alias hf="huggingface-cli"
```

Homebrew (or any other package manager) is not going to do this for you, because everyone has different preferences for how to set up their shell.

**Comment by Wauplin** [comment]
Thanks for the input @singingwolfboy. I think I'll close this issue then.
@remyleone please let me know if you have further questions and I'll reopen.
