### ISSUE TITLE
using hf_transfer should download shards in parallel not sequentially

### ISSUE THREAD

**Issue by tmabraham** [huggingface/huggingface_hub#1831]
**Is your feature request related to a problem? Please describe.**
I have observed when enabling `hf_transfer` that while the download of each shard in a repo is extremely fast, multiple shards are not downloaded in parallel. In contrast, downloading without `hf_transfer` enabled does seem to download shards in multiple processes but downloading speed in each process is slow. My understanding is that `hf_transfer` functions by dividing individual files into multiple chunks to download in multiple threads. 

**Describe the solution you'd like**
Would it also be possible to download multiple files simultaneously with `hf_transfer` enabled?

**Describe alternatives you've considered**
None that I think immediately think of, since `hf_transfer` is the only approach providing extremely fast download speeds per file. 

**Additional context**

**Comment by Wauplin** [comment]
Hey @tmabraham, you are indeed right. We are deactivating multithreading in Python when downloading with `hf_transfer`. This is because `hf_transfer` (written in Rust) is primarily designed to max-out the available bandwidth. As a result, multithreading in both Python and Rust shouldn't bring any beneficial advantage since the main bottleneck is the network bandwidth -or disk IO speed- rather than the cpu compute. In general it is not good practice to multitask a job in several layers since it can overload the machine - bringing a slow down instead of a speed-up.

That been said, you can still try it by yourself (I haven't tested myself). You can run `hf_hub_download`+`hf_transfer` on each shard file  in parallel and compare it to `snapshot_download`+`hf_transfer`.

**Comment by Wauplin** [comment]
(closing this issue as completed given https://github.com/huggingface/huggingface_hub/issues/1831#issuecomment-1814459972)
