### ISSUE TITLE
Show model/repo name when downloading

### ISSUE THREAD

**Issue by ultranity** [huggingface/huggingface_hub#1984]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when there is downloading some model but don't know which model is being downloaded as most model checkpoint in huggingface have same file name like "config.json", "model.bin"

**Describe the solution you'd like**
It's better to show the repo path or model name before specific file download progress

**Describe alternatives you've considered**
and more better if we can control whether to show detailed downloading progress or the total progress

**Comment by Wauplin** [comment]
> I'm always frustrated when there is downloading some model but don't know which model is being downloaded

It looks to me that this should be an issue for the high-level library that should tell you which model is been downloaded.

> It's better to show the repo path or model name before specific file download progress

I'm not so sure. I would expect users to know which models they are downloading but still wanting to know which files precisely are taking time. It's more of a "nice to have" to be honest. If we do the opposite (showing repo_id instead of filenames) all progress bars will look the same which wouldn't make more sense than having filenames.

> if we can control whether to show detailed downloading progress or the total progress

This should be possible once https://github.com/huggingface/huggingface_hub/issues/1595 is implemented but it has been quite low priority for now.

---
Another solution to you problem would be to set the log level to "info" instead of "warning" by default. You can do that using the Python's logging configuration or simply like this:
```py
from huggingface_hub import logging

logging.set_verbosity_info()
```

You'll see more logs in your terminal, including logs that tells you which file from which repo you are downloading.
