### ISSUE TITLE
list_models() returns no model_index and therefore no model cards

### ISSUE THREAD

**Issue by buhrmann** [huggingface/huggingface_hub#2025]
### Describe the bug

`list_models()` doesn't seem to correctly extract the `model_index`, which in turn seems to be necessary to get the associated model card.

### Reproduction

``` python
set(m.model_index for m in list_models(full=True, cardData=False))
>> {None}
```

And asking with `cardData=True` issues this warning:
```
/Users/thomas/micromamba/envs/grapy/lib/python3.9/site-packages/huggingface_hub/repocard_data.py:322: UserWarning: Invalid model-index. Not loading eval results into CardData.
  warnings.warn("Invalid model-index. Not loading eval results into CardData.")
```

### System info

```shell
- huggingface_hub version: 0.20.2
- Platform: macOS-14.0-arm64-arm-64bit
- Python version: 3.9.18
- Running in iPython ?: Yes
- iPython shell: ZMQInteractiveShell
- Running in notebook ?: Yes
- Running in Google Colab ?: No
- Token path ?: /Users/thomas/.cache/huggingface/token
- Has saved token ?: True
- Who am I ?: tomgxt
- Configured git credential helpers: osxkeychain
- FastAI: N/A
- Tensorflow: 2.15.0
- Torch: 1.9.1
- Jinja2: 3.1.2
- Graphviz: 0.20.1
- Pydot: N/A
- Pillow: 10.0.1
- hf_transfer: N/A
- gradio: N/A
- tensorboard: N/A
- numpy: 1.23.5
- pydantic: 1.10.13
- aiohttp: 3.9.1
- ENDPOINT: https://huggingface.co
- HF_HUB_CACHE: /Users/thomas/.cache/huggingface/hub
- HF_ASSETS_CACHE: /Users/thomas/.cache/huggingface/assets
- HF_TOKEN_PATH: /Users/thomas/.cache/huggingface/token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
- HF_HUB_ETAG_TIMEOUT: 10
- HF_HUB_DOWNLOAD_TIMEOUT: 10
```

**Comment by Wauplin** [comment]
Hi @buhrmann, when cardData is not requested, it is normal for the server not to return model-index. When `cardData=True`, the model index is expected to be returned. I suspect that the warning is raised because one of the returned model has a corrupted model index (e g. the model cars was created/modified before we added the validation rule). The warning is just saying that for that model the field is ignored (i.e. set to None) but other models should still be returned correctly.

**Comment by Wauplin** [comment]
Glad your issue has been solved! 
I suspect this is because ModelInfo is a dataclass object while ModelCardData is a simple class. We should update that to be more consistent.

**Comment by ademait** [comment]
Hi @Wauplin and @buhrmann, this also happened to me. When checking to which repositories it happens, I can not find it out. How could I check which repositories throw this warning?

Since I am just reading the repositories with `list_models` (parameters `full=True` and `cardData=True`), do I get the `ModelInfo` object when I get the warning? Or it just returns the warning?

I understand that the warning is thrown only by iterating over the models, since this also throws the warnings:
```
models = api.list_models(full=True, cardData=True, fetch_config=True, use_auth_token=ACCESS_TOKEN)
for m in models:
    continue
```

**Comment by ademait** [comment]
Hi, update here! I have seen in this issue #2057 that @Wauplin explains that the process keeps working, it is just a warning.

**Comment by Wauplin** [comment]
Yes indeed!
