### ISSUE TITLE
list_models(cardData = True) no longer functions

### ISSUE THREAD

**Issue by georgecolville** [huggingface/huggingface_hub#2057]
### Describe the bug

setting cardData to True when using list_models returns "Invalid model-index. Not loading eval results into CardData."

the identical code ran without an issue last week, and I cannot see any reason on my end it should have changed

### Reproduction

models = hf_api.list_models(full=True, cardData=True, sort='downloads', direction = -1)

modellist = list(models)
print(len(modellist))

### Logs

```shell
-
```

### System info

```shell
- huggingface_hub version: 0.21.1
- Platform: macOS-13.5.2-arm64-arm-64bit
- Python version: 3.11.5
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: /Users/-/.cache/huggingface/token
- Has saved token ?: True
- Who am I ?: printersdevil
- FastAI: N/A
- Tensorflow: N/A
- Torch: N/A
- Jinja2: N/A
- Graphviz: N/A
- Pydot: N/A
- Pillow: N/A
- hf_transfer: N/A
- gradio: N/A
- tensorboard: N/A
- numpy: 1.26.4
- pydantic: N/A
- aiohttp: N/A
- ENDPOINT: https://huggingface.co
- HF_HUB_CACHE: /Users/-/.cache/huggingface/hub
- HF_ASSETS_CACHE: /Users/-/.cache/huggingface/assets
- HF_TOKEN_PATH: /Users/-/.cache/huggingface/token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
- HF_HUB_ETAG_TIMEOUT: 10
- HF_HUB_DOWNLOAD_TIMEOUT: 10
```

**Comment by Wauplin** [comment]
@georgecolville, is it really failing though? If yes, please provide a stacktrace.

Since last week [we've released v0.21](https://huggingface.co/posts/Wauplin/967130417344883) which include https://github.com/huggingface/huggingface_hub/pull/1980 which changes how warnings are handled. Result is that for each model with a corrupted model-index you get a warning but the process still doesn't stop. It was the same before except that the warning message was handled differently.

I just tried both with V0.20.0 and V0.21.2 versions and got the same result:
```
# v0.20
/home/wauplin/projects/huggingface_hub/src/huggingface_hub/repocard_data.py:322: UserWarning: Invalid model-index. Not loading eval results into CardData.
  warnings.warn("Invalid model-index. Not loading eval results into CardData.")
530675
```
```
# v0.21
Invalid model-index. Not loading eval results into CardData.
Invalid model-index. Not loading eval results into CardData.
Invalid model-index. Not loading eval results into CardData.
(...)
Invalid model-index. Not loading eval results into CardData.
Invalid model-index. Not loading eval results into CardData.
530673
```
