### ISSUE TITLE
Does huggingface-cli support convert to safetensor .

### ISSUE THREAD

**Issue by nikhilzones** [huggingface/huggingface_hub#2078]
I have downloaded the model locally in my local disk , do we have some tool to convert .bin to .safetensor ?

**Comment by Wauplin** [comment]
Hi @nikhilzones, you can use this Space to convert the weights: https://huggingface.co/spaces/safetensors/convert. This is safer than the converting it on your local computer. Otherwise, we don't have a CLI tool per-se but you can check [these docs](https://huggingface.co/docs/safetensors/main/en/convert-weights) to help you get started locally.

**Comment by Wauplin** [comment]
I'm closing the issue but please let me know if you need more information :)
