### ISSUE TITLE
Cache folder gets created even if model name does not exist

### ISSUE THREAD

**Issue by poedator** [huggingface/huggingface_hub#2091]
### Describe the bug

model cache folder gets created even if model name does not exist. This is a nuicance as this creates junk folders in the cache folder.

suggestion: delete this line that creates cache folder prematurely, code seems to work without it:
https://github.com/huggingface/huggingface_hub/blob/e699a4e1a1e1fff71afb9b92097067f04ba283c3/src/huggingface_hub/file_download.py#L1214

### Reproduction

```
model_name_0 = "nobody/no_such_model"
model = transformers.AutoModelForCausalLM.from_pretrained(model_name_0, low_cpu_mem_usage=True)
```
then check TRANSFORMERS_CACHE folder to find the model cache folder named `models__nobody__no_such_model`

### System info

```shell
any system
```

**Comment by Wauplin** [comment]
Hi @poedator, thanks for reporting the issue! The suggested fix should work correctly indeed since subdirectories are created [here](https://github.com/huggingface/huggingface_hub/blob/e699a4e1a1e1fff71afb9b92097067f04ba283c3/src/huggingface_hub/file_download.py#L1409) anyway, after the repo existence check. Would you like to open a PR to fix it? Thanks in advance :)

**Comment by Wauplin** [comment]
Closing as done in https://github.com/huggingface/huggingface_hub/issues/2091. Thanks again!
