### ISSUE TITLE
`HF_HUB_DISABLE_SYMLINKS_WARNING` 

### ISSUE THREAD

**Issue by bxsajid** [huggingface/huggingface_hub#2179]
### Describe the bug

I am adding a model to an existing tool and after merging my code and running the whole tool I have started getting this error and I am concerned about this that if i would have to make specific changes into environment variable, wouldn't it be a extra step for the other tester? Kindly looking for any guidance on this! Thanks!

C:\Users\arsla\anaconda3\Lib\site-packages\huggingface_hub\file_download.py:148: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\arsla\.cache\huggingface\hub\models--sentence-transformers--average_word_embeddings_glove.6B.300d. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

### System info

```shell
- huggingface_hub version: 0.22.2
- Platform: Windows-10-10.0.22623-SP0
- Python version: 3.11.7
- Running in iPython ?: Yes
- iPython shell: ZMQInteractiveShell
- Running in notebook ?: Yes
- Running in Google Colab ?: No
- Token path ?: C:\Users\arsla\.cache\huggingface\token
- Has saved token ?: False
- FastAI: N/A
- Tensorflow: N/A
- Torch: 2.2.2
- Jinja2: 3.1.3
- Graphviz: N/A
- keras: N/A
- Pydot: N/A
- Pillow: 10.2.0
- hf_transfer: N/A
- gradio: N/A
- tensorboard: N/A
- numpy: 1.26.4
- pydantic: 1.10.12
- aiohttp: 3.9.3
- ENDPOINT: https://huggingface.co
- HF_HUB_CACHE: C:\Users\arsla\.cache\huggingface\hub
- HF_ASSETS_CACHE: C:\Users\arsla\.cache\huggingface\assets
- HF_TOKEN_PATH: C:\Users\arsla\.cache\huggingface\token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
- HF_HUB_ETAG_TIMEOUT: 10
- HF_HUB_DOWNLOAD_TIMEOUT: 10
```

**Comment by Wauplin** [comment]
> huggingface_hub cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\arsla.cache\huggingface\hub\models--sentence-transformers--average_word_embeddings_glove.6B.300d. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the HF_HUB_DISABLE_SYMLINKS_WARNING environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development

Hi @bxsajid this message is actually a warning, not an error, telling you that on your setup (Windows + no dev mode) the user experience when caching files will be slightly degraded due to symlinks not been supported. 

Setting `HF_HUB_DISABLE_SYMLINKS_WARNING=1` as environment variable will hide this warning but will not solve the root problem. Unfortunately, there is nothing you can really do to solve the root problem (we would have done it otherwise). Just for context, the limitations we are talking about are only relevant when downloading multiple versions of the same model (which hopefully doesn't happen very often).

Is it clearer now? Do you have additional questions related to this? If not, I think we can close this issue :)

**Comment by Wauplin** [comment]
Closing as no new context since 3 weeks ago.

**Comment by wu-diu-diu** [comment]
**To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator.** 。 Choosing to turn on Windows developer mode has certain security risks, and some misoperations may cause system crashes. So you can choose the second method, which is to run python as an administrator.
- Find the python interpreter for your project, right-click and select Run as administrator, then run your code in the terminal window.
- An easier way is to open your IDE as an administrator so that the warning doesn't appear when running the program in the IDE.

**Comment by LoaiAlmoallem** [comment]
> **To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator.** 。 Choosing to turn on Windows developer mode has certain security risks, and some misoperations may cause system crashes. So you can choose the second method, which is to run python as an administrator.
> 
> * Find the python interpreter for your project, right-click and select Run as administrator, then run your code in the terminal window.
> * An easier way is to open your IDE as an administrator so that the warning doesn't appear when running the program in the IDE.

Thank you that helped me
