### ISSUE TITLE
Change `HUGGINGFACE_CO_URL_TEMPLATE` with environment variable

### ISSUE THREAD

**Issue by BakerBunker** [huggingface/huggingface_hub#2244]
**Is your feature request related to a problem? Please describe.**
Users might share the pretrained checkpoints with net storage like [alist](https://alist-doc.nn.ci/en/docs/driver/base/) or [S3 http links](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ShareObjectPreSignedURL.html), and the url format differs from `HUGGINGFACE_CO_URL_TEMPLATE`, it will be convenient if we can override `HUGGINGFACE_CO_URL_TEMPLATE` with environment variable.

**Describe the solution you'd like**
Change
https://github.com/huggingface/huggingface_hub/blob/77803de41d85a51707926c280f57e44ddbb2d980/src/huggingface_hub/constants.py#L59
to
```python
HUGGINGFACE_CO_URL_TEMPLATE = ENDPOINT + os.getenv("HF_URL_TEMPLATE","/{repo_id}/resolve/{revision}/{filename}")
``` 

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by Wauplin** [comment]
Hi @BakerBunker, the `huggingface_hub` library is primarily made (and optimized) to download files from the Hugging Face Hub. For now, we do not want to have to maintain integrations with other providers/registries. So I'll close this issue opened as "won't fix" and we can reopen if we see more demand for it. 

(The maintenance topic is not about this specific env variable but more about the tweaks we would have to make over time to support new use cases. That's why we are not promoting the `HF_ENDPOINT` env variable either.)

cc @julien-c
