### ISSUE TITLE
hardware args in docs for creating inference endpoints are outdated

### ISSUE THREAD

**Issue by MoritzLaurer** [huggingface/huggingface_hub#2339]
The arguments in the docs for creating [inference endpoints](https://huggingface.co/docs/huggingface_hub/v0.23.3/en/package_reference/hf_api#huggingface_hub.HfApi.create_inference_endpoint) still follow the old naming convention: 
```
    instance_size="medium",
    instance_type="g5.2xlarge",
```

The correct new argument values are here: https://huggingface.co/docs/inference-endpoints/pricing
E.g.:
```
    instance_size="x1",
    instance_type="nvidia-a10g
```

**Comment by Wauplin** [comment]
Thanks for reporting @MoritzLaurer! This has been fixed by @co42 in  https://github.com/huggingface/huggingface_hub/pull/2282. Docs from `main` have been updated (see https://huggingface.co/docs/huggingface_hub/main/en/package_reference/hf_api#huggingface_hub.HfApi.create_inference_endpoint) but it has not been officially released yet.
