### ISSUE TITLE
`snapshot_download` should ideally provide a similar API experience to `load_dataset` (subdirectory download support)

### ISSUE THREAD

**Issue by Lauler** [huggingface/huggingface_hub#2376]
**Is your feature request related to a problem? Please describe.**
The most common way of loading datasets in HF ecosystem is through `load_dataset`. This function offers convenient ways of loading specific splits or subsets (subdirectories) of the data. A very common use case for large datasets is to only download/load subsets of data.

When a library contains multiple functions that offer similar functionality, it can be helpful for users if those functions -- when possible -- have support for similar arguments and provide a consistent user experience. When API design needlessly differs it can cause frustration and annoyance among users.

I believe `snapshot_download` should ideally have a subdirectory/name argument that downloads all files in a specific subset/subdirectory of a dataset. This would help make the function more similar to `load_dataset` and make it easier to use/understand. 

**Describe the solution you'd like**
`snapshot_download` internally uses `hf_hub_download` to download single files. `hf_hub_download` has a `subfolder` argument already but only allows download of single files. 

I'd like to see a `subfolder` argument in `snapshot_download`, where the default behavior when specified is that every file in that subdirectory is downloaded. 

*Edit: I am aware `snapshot_download` offers a [filename filter functionality](https://huggingface.co/docs/huggingface_hub/en/guides/download#filter-files-to-download). Using this functionality to download subdirectories however heavily depends on the file naming conventions used by users who upload datasets. I maintain a `subfolder` argument provides a better experience for the common use case of wanting to download a subset of a dataset, and offers an experience that is consistent with `load_dataset`.

**Comment by Wauplin** [comment]
Hi @Lauler, thanks for raising the question. As far as I know, `load_dataset` don't have a `subfolder` parameter (see [docs](https://huggingface.co/docs/datasets/v2.20.0/en/package_reference/loading_methods#datasets.load_dataset)). You can indeed download splits or subsets but that's quite specific to datasets. Regarding the `subfolder` parameter from `hf_hub_download`, to be honest this is more a legacy parameter that is not much used to my knowledge since providing a full path as `filename` does the trick as well.

Regarding adding a `subfolder` parameter to `snapshot_download`, I don't really see the point -except maybe for documentation purposes-. As you said, there is already a filename filter available that does the same:

```py
snapshot_download("HuggingFaceFW/fineweb", repo_type="dataset", allow_patterns="data/*")
```

and 

```py
snapshot_download("HuggingFaceFW/fineweb", repo_type="dataset", subfolder="data/")
```

would be strictly equivalent. You don't have to know more about the file naming convention of the repository.

**Comment by Lauler** [comment]
Thanks for your response and sorry I did not read `load_dataset` doc carefully before writing the issue. I am basically referring to the `name` arg that allows users to download subsets that are often (not always) organized as a subfolders in practice. 

Thanks for your suggestion with `data/*`. Even though it should perhaps be obvious one can use wildcards like this to select everything in a subfolder, I did not actually make this connection myself after reading the huggingface_hub documentation and guides. I am someone who uses wildcards all the time in terminal and in python and yet I was stupid enough not to try the obvious even after reading the docs. 

I think chances are people who are less experienced and haven't encountered wildcards will be even less likely to discover how to emulate basic `load_dataset` behavior with `snapshot_download`. I would suggest having an explicit example in the [filename filter guide](https://huggingface.co/docs/huggingface_hub/en/guides/download#filter-files-to-download). 

To be honest I spent more than one hour being confused at the difference between `hf_hub_download`, `snapshot_download` and `load_dataset` because I am your typical user that skims the documentation too fast and just tries to use the functions. Here's a list of fails that lead to this issue:

1. At first I did not specify `repo_type=dataset` because as a dumb user I haven't thought through the fact that simply copying repository names is not enough for `huggingface_hub` to distinguish between datasets and models (don't know whether in hindsight it would have been more user friendly to have this info in the repository name that is copied from HF). 
2. Trying to use `hf_hub_download` instead of `snapshot_download` because it has a subfolder argument that I mistook as perhaps being equivalent to config name in `load_dataset` . I assumed HF would want the experience/API to be similar. 
3. Trying to use `hf_hub_download` like `snapshot_download` because I didn't read carefully enough to see that `snapshot_download` uses `hf_hub_download` internally to download **individual** files. 
4. Switching to `snapshot_download`, reading the docs and guides a bit more carefully and thinking `snapshot download` must have some kind of way of passing the subfolder to the function it is using internally. 
5. Trying lots of stupid combinations of arguments and appending stuff to repo_id, and for some reason just assuming your wildcard system was limited (so no thought at all about actually specifying the folder name there first). 

A last point of feedback: If `snapshot_download` can do everything that `hf_hub_download` does (including download individual files), maybe it would be wiser for the library to focus all the guides on `snapshot_download` and hide away `hf_hub_download`. Stupid users that don't have 15-30 minutes to read guides and docs carefully are inevitably going to be confused.

**Comment by Wauplin** [comment]
Thanks for explaining your process of thoughts @Lauler. I can see how misleading these were :confused: 
I feel that most of the confusion comes from `hf_hub_download`/`snapshot_download` naming that could just be named `download_file`/`download_folder`. We won't change naming because of historical reasons (and somehow people got used to the current naming) except if we see a good reason of doing it. 

Regarding `snapshot_download`/`hf_hub_download` vs `load_dataset`, there is no real incentive of merging the parameters names/features. I feel like they have different purposes from different libraries.
