### ISSUE TITLE
Inference API wrapper: adding parameters documentation

### ISSUE THREAD

**Issue by ferdi05** [huggingface/huggingface_hub#256]
I'd like to use some parameters when calling the inference API with `huggingface_hub.inference_api`.
e.g.: `"wait_for_model": True`

Can we add documentation to explain how to use it?

**Comment by osanseviero** [comment]
What specific parameters did you have in mind?

For `wait_for_model` in particular, it's always set to True. There was some discussion about this in #65, https://github.com/huggingface/huggingface_hub/pull/65#discussion_r644628072 in particular.

Feel free to check the code [here](https://github.com/huggingface/huggingface_hub/blob/main/src/huggingface_hub/inference_api.py#L93) since it's relatively simple. The only parameter that we should likely document is `use_gpu` but that should likely go in the Inference API documentation.

**Comment by ferdi05** [comment]
I was thinking `wait_for_model` and `use_gpu`and you answered to everything. Thanks very much !
