### ISSUE TITLE
Issue: TypeError: HfApi.upload_large_folder() got an unexpected keyword argument 'path_in_repo' 

### ISSUE THREAD

**Issue by anurag12-webster** [huggingface/huggingface_hub#2563]
My code:

```
from huggingface_hub import HfApi
api = HfApi()

api.upload_large_folder(
    folder_path = "./brazilian-portuguese",
    path_in_repo = "./pt/clips/",
    repo_id = "ModelsLab/Brazilian-Portuguese-Finetune",
    repo_type = "dataset"
)
```
It would be good if we can use the keyword ```path_in_repo``` while using the ```upload_large_folder()```.

**Comment by Wauplin** [comment]
Hi @anurag12-webster, sorry for the inconvenience. As mentioned [in the docs](https://huggingface.co/docs/huggingface_hub/guides/upload#upload-a-large-folder), `path_in_repo` is indeed not supported:

> [!WARNING]  
> you cannot set a custom path_in_repo. If you want to upload to a subfolder, you need to set the proper structure locally.

This is due to a technical limitation. If we allow `path_in_repo`, the cache system might be corrupted when launched with different path in repo. The best solution is to mimic the file structure locally.

**Comment by anurag12-webster** [comment]
Thanks @Wauplin appreciated🤗
