### ISSUE TITLE
Upload folder fails for a parquet file inside folder

### ISSUE THREAD

**Issue by sleepingcat4** [huggingface/huggingface_hub#2574]
### Describe the bug

I have a weird bug where when I tried to upload a 370 GB folder on HF through HFapi and for a particular file, it raised an error. And didn't say what the error was. Including the lack of options available on upload_folder option, make it unbearable. 

I diagnosed the error and one of my parquet files had None rows. Which was intended. But HF doesn't like this mismatch. It's quite frustrating since the column schema is same except the data format is changed (some are None rows). 

I don't have enough RAM to make one giant parquet file since I have only 250GB RAM. If I am not wrong Kaggle does not create such problems. Also the print statement is really bad on HF. It's high level which is super-cool but it does not let me diagnose my problem easily. 

Most importantly: Now I have to zip my folder which means I have to spend couple of long hours of compute to zip and then user who download my dataset have to spend another couple of long hours (depending on their system) to unzip the folder again. It costs compute and valuable time both for me and the end-user. 

I would appreciate if HF allowed only the schema of the columns to be same and not their data types. Maybe provide me a warning or an option to prevent an error like this from happening. 

Also HF's function for upload_large_folder is not working and can't be found by the HFapi

### System info

```shell
- huggingface_hub version: 0.24.5
- Platform: Linux-6.8.0-40-generic-x86_64-with-glibc2.39
- Python version: 3.12.3
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: /home/ammar/.cache/huggingface/token
- Has saved token ?: True
- Who am I ?: sleeping4cat
- Configured git credential helpers:
- FastAI: N/A
- Tensorflow: N/A
- Torch: N/A
- Jinja2: N/A
- Graphviz: N/A
- keras: N/A
- Pydot: N/A
- Pillow: N/A
- hf_transfer: N/A
- gradio: N/A
- tensorboard: N/A
- numpy: 1.26.4
- pydantic: N/A
- aiohttp: 3.10.3
- ENDPOINT: https://huggingface.co
- HF_HUB_CACHE: /home/ammar/.cache/huggingface/hub
- HF_ASSETS_CACHE: /home/ammar/.cache/huggingface/assets
- HF_TOKEN_PATH: /home/ammar/.cache/huggingface/token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
- HF_HUB_ETAG_TIMEOUT: 10
- HF_HUB_DOWNLOAD_TIMEOUT: 10
```

**Comment by Wauplin** [comment]
Hi @sleepingcat4 sorry you are facing this but that's a lot of unrelated issues been reported at the same time.

> and for a particular file, it raised an error. And didn't say what the error was.

What error has been raised exactly? Can you see the file on the Hub?

> Including the lack of options available on upload_folder option, make it unbearable.

Which option would you like to see?

> I diagnosed the error and one of my parquet files had None rows. Which was intended. But HF doesn't like this mismatch. It's quite frustrating since the column schema is same except the data format is changed (some are None rows).

The Hugging Face Hub doesn't have any constraint on which file you should upload. It doesn't parse your parquet file at all so a problem of `None` columns is not possible. Maybe there is a corner case if a file is empty (0 bytes) but I'd be surprised. In any case, if you have a clear error, please share it.

>  Now I have to zip my folder which means I have to spend couple of long hours of compute to zip and then user who download my dataset have to spend another couple of long hours (depending on their system) to unzip the folder again. It costs compute and valuable time both for me and the end-user.

That would be indeed annoying but it's not the case. Any file can be uploaded. There are some rules to follow (not more than 100k files per repo, 10k files per folder) but I doubt you reached these limits. More details here: https://huggingface.co/docs/hub/repositories-recommendations

> Also HF's function for upload_large_folder is not working and can't be found by the HFapi

You most likely need to upgrade `huggingface_hub` to latest version 


----

If your problem is specifically related to the `datasets` library (which is more opinionated on parquet files) or to the `dataset viewer`, please report the precise issue to their repo instead.
