### ISSUE TITLE
Unable to install huggingface-cli

### ISSUE THREAD

**Issue by Ra8aels** [huggingface/huggingface_hub#2619]
### Describe the bug

I run this on Pop!_OS

When I run:
`pip install -U "huggingface_hub[cli]"`

I get this output:
`Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: huggingface_hub[cli] in ./.local/lib/python3.10/site-packages (0.26.0)
Requirement already satisfied: filelock in ./.local/lib/python3.10/site-packages (from huggingface_hub[cli]) (3.16.1)
Requirement already satisfied: fsspec>=2023.5.0 in ./.local/lib/python3.10/site-packages (from huggingface_hub[cli]) (2024.6.1)
Requirement already satisfied: packaging>=20.9 in ./.local/lib/python3.10/site-packages (from huggingface_hub[cli]) (24.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/lib/python3/dist-packages (from huggingface_hub[cli]) (5.4.1)
Requirement already satisfied: requests in ./.local/lib/python3.10/site-packages (from huggingface_hub[cli]) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in ./.local/lib/python3.10/site-packages (from huggingface_hub[cli]) (4.66.5)
Requirement already satisfied: typing-extensions>=3.7.4.3 in ./.local/lib/python3.10/site-packages (from huggingface_hub[cli]) (4.12.2)
Requirement already satisfied: InquirerPy==0.3.4 in ./.local/lib/python3.10/site-packages (from huggingface_hub[cli]) (0.3.4)
Requirement already satisfied: pfzy<0.4.0,>=0.3.1 in ./.local/lib/python3.10/site-packages (from InquirerPy==0.3.4->huggingface_hub[cli]) (0.3.4)
Requirement already satisfied: prompt-toolkit<4.0.0,>=3.0.1 in ./.local/lib/python3.10/site-packages (from InquirerPy==0.3.4->huggingface_hub[cli]) (3.0.48)
Requirement already satisfied: charset-normalizer<4,>=2 in ./.local/lib/python3.10/site-packages (from requests->huggingface_hub[cli]) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests->huggingface_hub[cli]) (3.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/lib/python3/dist-packages (from requests->huggingface_hub[cli]) (1.26.5)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests->huggingface_hub[cli]) (2020.6.20)
Requirement already satisfied: wcwidth in ./.local/lib/python3.10/site-packages (from prompt-toolkit<4.0.0,>=3.0.1->InquirerPy==0.3.4->huggingface_hub[cli]) (0.2.13)`

### Reproduction

After that I tried this command:
`huggingface-cli login`

Then I got this error:
`huggingface-cli: command not found`

### Logs

```shell
Python version - Python 3.10.12
Linux distro - Pop!_OS
GPU(Idk how this changed it) - Nvidia GTX 1070 Ti
```

### System info

```shell
huggingface-cli: command not found
```

**Comment by hanouticelina** [comment]
hi @Ra8aels, the output you've shared does not indicate any errors. Instead, it confirms that all the required packages for `huggingface_hub[cli]` and its dependencies are already installed. Here is how I would have debugged this issue:
1 - verify that `huggingface-cli` script is correctly installed by checking that it exists in `~/.local/bin/*`: 
```bash
ls ./.local/bin
```
if you see `huggingface-cli` there it means it's correctly installed and you can run `./.local/bin/huggingface-cli login`.
2 - now you have two possible solutions:
- either you add `~/.local/bin` to your `PATH` environment variable so that your shell can find the `huggingface-cli` command.
- or alternatively, you can use a virtual environment, which isolates your python packages and ensures scripts are available within that environment.

I hope this helps! I will close this issue but feel free to comment if you have another question 🤗
