### ISSUE TITLE
Single link downloads limited to like 40 megabytes per second can we make snapshot_download to open multi connection and download faster?

### ISSUE THREAD

**Issue by FurkanGozukara** [huggingface/huggingface_hub#2658]
### Describe the bug

Example case

![image](https://github.com/user-attachments/assets/ca67985f-42ea-460a-b8cc-9a8742b13604)

This server has over 1 Gbit download speed

If i start multiple files fetch all combined reaches 300 megabytes per second +
lets say repo has 10 files so total combined speed is over 300 megabytes per second with `snapshot_download`

however when downloading single file limited to only 40 megabytes per second

i tested this in so many places and cases

can we make `snapshot_download `to open multiple connections for per single download link?

this is how i download single file

```
        snapshot_download(
            repo_id="Kijai/flux-fp8",
            allow_patterns="flux1-dev-fp8.safetensors",
            local_dir=f"{base_Path}/diffusion_models"
        )
```

**Comment by Wauplin** [comment]
Hi @FurkanGozukara, there are a few things to say here:
- best way to download a single file is to use `hf_hub_download` instead of `snapshot_download` (less logic but sill same speed)
- when downloading multiple files with `snapshot_download`, you can set `max_workers=...` to increase the number of parallel downloads. There will still be 1 connection per file.
- to maximize download speed on a big machine, you can use `hf_transfer` which is specifically dedicated to this. You have to `pip install hf_transfer` and then run your script with `HF_HUB_ENABLE_HF_TRANSFER=1` as environment variable. Code remains exactly the same but the file will be downloaded by a specific client written in Rust that will try to use all the available bandwidth -and all cores of your CPU-. More details here: https://huggingface.co/docs/huggingface_hub/hf_transfer.

Hope this will prove useful to you! I'm closing this issue as it's not really a bug/issue to fix.

**Comment by FurkanGozukara** [comment]
@Wauplin this is just amazing thank you so much

this is on my local pc

![image](https://github.com/user-attachments/assets/7b5f2200-7dbb-4de8-804f-4066f28ba7ce)
