### ISSUE TITLE
ImportError: cannot import name 'ModelFilter' from 'huggingface_hub' 

### ISSUE THREAD

**Issue by SaiPavankumar22** [huggingface/huggingface_hub#2710]
### Describe the bug

internal dependency is trying to import ModelFilter from the huggingface_hub library, but the installed version of huggingface_hub does not include this class. The issue is caused by a version mismatch between the huggingface_hub library and the version expected by NVIDIA NeMo.

### System info

```shell
- huggingface_hub version: 0.24.0
- Platform: Linux-6.8.0-45-generic-x86_64-with-glibc2.35
- Python version: 3.10.12
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Has saved token ?: False
- Configured git credential helpers: 
- FastAI: N/A
- Tensorflow: N/A
- Torch: 2.5.1
- Jinja2: 3.1.4
- Graphviz: 0.20.3
- keras: N/A
- Pydot: N/A
- Pillow: 10.4.0
- hf_transfer: N/A
- gradio: 5.8.0
- tensorboard: N/A
- numpy: 1.23.5
- pydantic: 2.10.3
- aiohttp: 3.11.10
- ENDPOINT: https://huggingface.co
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
- HF_HUB_ETAG_TIMEOUT: 10
- HF_HUB_DOWNLOAD_TIMEOUT: 10
```

**Comment by hanouticelina** [comment]
Hi @SaiPavankumar22 - ModelFilter was removed from `huggingface_hub` since v0.24. Based on this comment (https://github.com/NVIDIA/NeMo/issues/10272#issuecomment-2323120215), `ModelFilter` is no longer used in their code. There's nothing we can do on our side and it has been fixed in the NVIDIA/NeMo repo. I suggest updating your local repo to be in sync with the main branch of https://github.com/NVIDIA/NeMo. 
I hope this helps!

I will close this issue but feel free to comment if you have any related question :)
