### ISSUE TITLE
`hf_hub_download` does not pre-cache files for `Model.from_pretrained`

### ISSUE THREAD

**Issue by xhlulu** [huggingface/huggingface_hub#601]
In [this tutorial](https://huggingface.co/docs/hub/how-to-downstream), it seems to imply that the huggingface-hub function `hf_hub_download` is useful for pre-caching model pretrained weights:

> cached_download is useful for downloading and caching a file on your local disk. Once stored in your cache, you don't have to redownload the file the next time you use it. cached_download is a hands-free solution for staying up to date with new file versions.

Moreover, calling `Model.from_pretrained` will not actually automatically load the weights downloaded with `hf_hub_download`. It would be nice if this would be supported, or otherwise an example on how to load from cache could be added since this scenario would be often relevant.

**Comment by LysandreJik** [comment]
Hi @xhlulu, that's a very good point! I believe that with `Model.from_pretrained`, you're using `transformers` models?

This is due to `transformers` saving in `$CACHE_DIR/transformers/<etag>`, and `huggingface_hub` saving in `$CACHE_DIR/hub/<etag>`. It would require minimal changes to have `transformers` look for the files in the `hub` folder.

A small issue with enabling this is that this simple change would only enable partial support for the files downloaded with `hfh`, as `snapshot_download` would not work -> it downloads the files in the same folder, but it downloads the entire repository, which ends up with a different identifier than the files downloaded with `hf_hub_download`.

Since these two can be resolved independently, I don't think it's an issue to go ahead and enable the support of `hf_hub_download` on `transformers` side as a first step.

**Comment by xhlulu** [comment]
That would be amazing!

**Comment by LysandreJik** [comment]
We're working on omething a bit better, happening here: https://github.com/huggingface/huggingface_hub/pull/801

All the caches across all libraries will be unified :)
