### ISSUE TITLE
List all datasets or models using token

### ISSUE THREAD

**Issue by osanseviero** [huggingface/huggingface_hub#634]
As of now, `list_models` and `list_datasets` don't use the token, so they only list public models. If we could pass the token here, it would be very useful to do things such as retrieving all datasets (including private) of an organization.

cc @muellerzr @LysandreJik 

https://github.com/huggingface/huggingface_hub/blob/main/src/huggingface_hub/hf_api.py#L511

**Comment by muellerzr** [comment]
At one point we thought on this, now that there's a need would be a decent idea to implement that again. Can put that on my list :)

**Comment by LysandreJik** [comment]
Good issue! This would require a `use_auth_token` parameter rather than a `token` parameter that would automatically fetch the current logged-in user's token, as we could envision users wanting to use `list_{models,datasets}` without the private models.

The `use_auth_token` would behave similarly to others in the library, i.e., `None` by default, if `True` will fetch the current logged-in user's token, and if it is a string then will use that as the token.

Let me know if you want to tackle that @muellerzr otherwise I'll do it in a bit.
