### ISSUE TITLE
Repository does not work with Spaces

### ISSUE THREAD

**Issue by osanseviero** [huggingface/huggingface_hub#672]
If I create a space and then do

```python
repo = Repository(local_dir=local_dir, clone_from="https://huggingface.co/space/osanseviero/this-is-a-test12345", repo_type="space")
```

I get following error

ValueError: No space_sdk provided. `create_repo` expects space_sdk to be one of ['gradio', 'streamlit', 'static'] when repo_type is 'space'`

cc @nateraw @LysandreJik @muellerzr

**Comment by nateraw** [comment]
Did you mean `repo = Repository(local_dir=local_dir, clone_from="https://huggingface.co/spaces/osanseviero/this-is-a-test12345", repo_type="space")` with "spaces" in the URL? (I haven't tried, just a thought)

**Comment by osanseviero** [comment]
Actually with spaces it also fails.

I tried to debug a bit more. It fails when I'm the owner of the space and works when it's another unrelated space

**Comment by osanseviero** [comment]
This is the src https://github.com/huggingface/huggingface_hub/blob/main/src/huggingface_hub/repository.py#L545-L552

**Comment by muellerzr** [comment]
Nice catch. this is because `Repository` won't actually take in a `space_sdk` during it's init, so nothing get's passed when performing https://github.com/huggingface/huggingface_hub/blob/main/src/huggingface_hub/hf_api.py#L1081

Pretty sure the solution would be to give `Repository` a `space_sdk` param that can be passed down? WDYT @LysandreJik

**Comment by osanseviero** [comment]
I don't love the idea because it's annoying when combined with `create_repo` or when cloning an existing space created through the UI. We're expecting the user to specify the sdk both in `create_repo` and again in `Repository`.

One solution could be to:
* Check before internal `create_repo` call if the repo exists. If it exists, let's not call it.
* Add a `space_sdk` param as well, but now it won't be obligatory for all spaces

**Comment by julien-c** [comment]
isn't it weird API-wise that `Repository`'s init creates a repo for you on the fly if needed?

Shouldn't it be a different method to better separate intents, like a static `Repository.create(...) -> Repository`?

**Comment by julien-c** [comment]
what's `huggingface_hub` policy on breaking changes? we can maybe keep BC for a few months then drop it?

**Comment by LysandreJik** [comment]
Even if I think that `Repository`'s ability to create a repository on the fly reduces the mental load, I understand that it can be a bit weird and that it can be surprising. However, I'd rather we have one way of doing things rather than several methods which do a very similar thing.

If everyone thinks that `Repository` shouldn't create the repo on the fly, then IMO we should remove the repo creation and push `create_repo`, but not `Repository.create`.

I personally think `Repository.create(...) -> Repository` is as ambiguous as `Repository(..., clone_from="xxx")` creating the `xxx` repository remotely; but `create_repo(...); Repository(...)` is not ambiguous.

**Comment by julien-c** [comment]
Hmm, why do you say that `Repository.create(...) -> Repository` is ambiguous?

**Comment by LysandreJik** [comment]
I don't remember why I thought it was ambiguous, but I still think having `create_repo` create the repo and `Repository` handle the repository without creating it is simpler. Will open a PR unless there are objections.

**Comment by merveenoyan** [comment]
Is there any update on this? 
I went to all linked PRs and issues but nothing seems to be up? I did pass `space_sdk` to `create_repo` and `repo_type` to both `Repository` and `create_repo` and I still get the same error 🥺
I made sure I have most recent version of Hub. 
```
(py39) ➜  dataset_profiling git:(main) ✗ pip3 freeze | grep huggingface-hub
huggingface-hub==0.7.0
```
My code is below:
```
url = create_repo(f"{username}/{dataset_name}", repo_type = "space", token = token, space_sdk = "static")
    repo = Repository(
        local_dir = f"{username}/{dataset_name}",
        clone_from=url,
        use_auth_token=token,
        repo_type = "space"
    )
```
feel free to bash me if I do anything unexpected 😅

**Comment by merveenoyan** [comment]
Very weird finding, when I don't give `use_auth_token` when creating a repository it works fine but when I give it I get the error, maybe it's unrelated though.
