### ISSUE TITLE
Error in creating repository 

### ISSUE THREAD

**Issue by Jeevesh8** [huggingface/huggingface_hub#695]
I am getting the following error:
```
File "./run_flax_glue.py", line 638, in <module>
    main()
  File "./run_flax_glue.py", line 330, in main
    HfApi().create_repo(repo_name, token=training_args.hub_token)
  File "/ext3/miniconda3/lib/python3.9/site-packages/huggingface_hub/hf_api.py", line 1078, in create_repo
    raise err
  File "/ext3/miniconda3/lib/python3.9/site-packages/huggingface_hub/hf_api.py", line 1067, in create_repo
    r.raise_for_status()
  File "/ext3/miniconda3/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://huggingface.co/api/repos/create - Internal Error - We're working hard to fix that as soon as possible!
```

I tried creating model on HuggingFace Hub, using the website and was able to. I tried updating my key, to no avail. This error has been showing since yesterday. Is this really some error on your(server) side? Or is an error on my side only?

Yours gratefully,

**Comment by mahalakshmijinadoss** [comment]
I am facing issues while trying to create a repository as well. This error has been showing since yesterday. Is this some error on your(server) side? Or is it an error on my side only? Thank you. I am getting the following error message

HTTPError: 500 Server Error: Internal Server Error for url: https://huggingface.co/api/repos/create - Internal Error - We're working hard to fix that as soon as possible!

**Comment by osanseviero** [comment]
We're looking into it, thanks for reporting!

**Comment by osanseviero** [comment]
This should be fixed now 😄 🚀

**Comment by mahalakshmijinadoss** [comment]
It works now. Thank you!
