### ISSUE TITLE
[Feature Request] Add "git clone XXXXX" snippet for Spaces

### ISSUE THREAD

**Issue by cakiki** [huggingface/huggingface_hub#842]
**Is your feature request related to a problem? Please describe.**
There currently is no copiable snippet for spaces to clone them locally.

**Describe the solution you'd like**
A similar behavior to `transformers` and `datasets` that provides the `git clone xxxxxx` copy button.

**Describe alternatives you've considered**
Manually constructing the git link.

**Additional context**
N/A

**Comment by julien-c** [comment]
[[internal issue/PR](https://github.com/huggingface/moon-landing/pull/2347)]

**Comment by Wauplin** [comment]
(closing issue as it's now available through the "duplicate space" modal)

![2023-01-19_15-34](https://user-images.githubusercontent.com/11801849/213469713-848a4816-b358-4fb6-a30b-676d500641eb.png)

**Comment by blefaudeux** [comment]
my two cents, for what it's worth: the UI is very strange here for people used to GitHub (everyone ?), because "duplicate" looks like "fork" (similar position in the UI, top right) and nobody would confuse fork and clone. There's an option to copy in one click, but that doesn't expose the remote, just the repo name, and I just spent 3 minutes looking for the remote only to fall here after a search.

`git clone` has to be one of the top 3 actions that interested people would do when landing on a new repo (aka space). That this is not accessible directly following the UI (you have to open a menu and be told that you did it wrong -'don't' is negative-) while something else (copy the repo name) is one click feels a little backwards.

**Comment by julien-c** [comment]
@blefaudeux we'll take alook
