### ISSUE TITLE
Add filename as args to fastai method from_pretrained_fastai

### ISSUE THREAD

**Issue by kurianbenoy** [huggingface/huggingface_hub#859]
**Is your feature request related to a problem? Please describe.**

Yes, using `from_pretrained_fastai` is very helpful, yet we can just use only modelnames with `model.pkl` due to the code.

https://github.com/huggingface/huggingface_hub/blob/main/src/huggingface_hub/fastai_utils.py#L349

 I commonly upload models name other than 'model.pkl'. So I want a customizable option to pass filenames from my model repository.

**Describe the solution you'd like**

Add a fname argument, and with it pass whatever model name I want to pass.

**Describe alternatives you've considered**

None

**Comment by osanseviero** [comment]
WDYT @LysandreJik @omarespejel?

@kurianbenoy, usually we push for standardizing filenames on the Hub. E.g. all PT models are `pytorch_model.bin`, all JAX/Flax models are `flax_model.msgpack`, etc. Note that `push_to_hub_fastai` saves the model with `model.pkl` name, so if you use that method you should not have problems.

**Comment by omarespejel** [comment]
Thanks @kurianbenoy!

**Problem**: In the current form, if a user (1) did not use `push_to_hub_fastai` to share her Learner, and (2) she did not name her pkl as `model.pkl`; then `from_pretrained_fastai` would not work. 

Actually, in a previous commit of  `push_to_hub_fastai` we decided to eliminate the functionality to allow for other pkl names due to the same reasons @osanseviero explained.

**Comment by kurianbenoy** [comment]
The explanation @osanseviero makes totally sense to me. For normal users then there is the alternative option as well with ` hf_hub_download` too.

I am closing this issue. Feel free to reopen in case of any further discussions happen

**Comment by omarespejel** [comment]
Thank you @kurianbenoy!
