### ISSUE TITLE
Ignore file patterns when uploading a folder

### ISSUE THREAD

**Issue by osanseviero** [huggingface/huggingface_hub#982]
It would be great if `upload_folder` could support a parameter to ignore file patterns. For example, I might want to use `upload_folder` but ignoring `.onnx` files or another file pattern (e.g. files under certain directories such as files from vscode, etc).

**Comment by Wauplin** [comment]
Seems legitimate. We can use [fnmatch](https://docs.python.org/3/library/fnmatch.html) library to do the pattern matching on each file path. For simple patterns (`ignore_patterns=["*.onnx"]`), I don't see any problem.

For patterns including folder paths (`"*/something/*.onnx"`), do you know if that works as well on Windows ?

**Comment by LysandreJik** [comment]
Good request! I think we could do it like we do it in `snapshot_download`: https://github.com/huggingface/huggingface_hub/blob/c16c3185e5d2e8d64f595e2cc1ea5bd7a96e4af5/src/huggingface_hub/_snapshot_download.py#L55-L56

We have `allow_regex` and `ignore_regex` as parameters.

We then filter using fnmatch as you have mentioned @Wauplin:

https://github.com/huggingface/huggingface_hub/blob/c16c3185e5d2e8d64f595e2cc1ea5bd7a96e4af5/src/huggingface_hub/_snapshot_download.py#L15-L38

**Comment by Wauplin** [comment]
Good to know, thanks for the reference @LysandreJik ! Then something similar could also be added to `upload_folder` and then reuse the `_filter_repo_files`.

---
From a naming perspective, isn't it `allow_regex` misleading since `fnmatch` is not exactly regex but "Unix shell-style wildcards" ? See https://docs.python.org/3/library/fnmatch.html:
> This module provides support for Unix shell-style wildcards, which are *not* the same as regular expressions.

What do you think about deprecating `allow_regex `/`ignore_regex` in favor of `allow_pattern`/`ignore_pattern` ?

**Comment by LysandreJik** [comment]
Sure, this was proposed in https://github.com/huggingface/huggingface_hub/issues/836 but we never got to it. If you'd like to tackle this issue, please go ahead :raised_hands:
